package com.simhastha.view;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;

/** Temporary UI data provider. A future Firebase repository can replace this boundary. */
public final class AnnouncementDemoStore {
    public enum Priority { CRITICAL, HIGH, IMPORTANT, NORMAL }
    public record Announcement(String id, String title, String shortDescription, String fullDescription, String category,
            Priority priority, String department, String status, LocalDateTime publishedAt, LocalDateTime lastUpdated,
            LocalDateTime validUntil, boolean hasLocation, String locationName, String address, String zone, String sector,
            String camp, String ghat, double latitude, double longitude, boolean locationChange, String previousLocation,
            String newLocation, String changeReason, String affectedArea, boolean actionRequired, String actionInstruction,
            String alternativeLocation, String alternativeRoute, boolean showDashboardAlert, boolean emergencyBanner) { }
    private static final List<Announcement> ITEMS = new ArrayList<>();
    private static final Set<String> READ = new HashSet<>();
    private static final Set<String> BOOKMARKED = new HashSet<>();
    static {
        LocalDateTime now = LocalDateTime.now();
        ITEMS.add(item("aarti-change", "Aarti Location Changed", "Today's evening Maha Aarti has moved to a new venue.", "For crowd management, follow the marked route and volunteer directions for today's Aarti.", "Event / Religious", Priority.CRITICAL, "Simhastha Administration", "LIVE", now.minusMinutes(35), now.minusMinutes(5), now.plusHours(2), true, "Aarti Ghat — Sector B", "Godavari riverfront, Sector B", "Godavari Zone", "Sector B", "Aarti Camp", "Aarti Ghat", 20.0064, 73.7904, true, "Ram Ghat", "Aarti Ghat — Sector B", "Crowd management", "Godavari Zone / Sector B", true, "Proceed to Sector B using Gate 3.", "Godavari Ghat — Sector C", "Use the eastern pedestrian route.", true, true));
        ITEMS.add(item("ramkund-crowd", "Ram Ghat Crowd Advisory", "Use the eastern pedestrian approach between 5:00 PM and 8:00 PM.", "Police teams have set up barricades around Ram Ghat. Avoid the main approach until the crowd advisory ends.", "Ghat / Crowd", Priority.HIGH, "Nashik Police", "LIVE", now.minusHours(1), now.minusMinutes(20), now.plusHours(3), true, "Ramkund East Entry", "Near Panchavati east approach", "Panchavati", "East Entry", "", "Ramkund Ghat", 20.0060, 73.7900, false, "", "", "", "Ramkund and Panchavati", true, "Use Gate 3 instead of Gate 1.", "Godavari Ghat — Sector C", "Follow eastern pedestrian signage.", true, false));
        ITEMS.add(item("parking-change", "Parking Area Changed", "Pilgrim parking has moved to Panchavati North lot.", "The previous parking area is reserved for emergency vehicles. Shuttle support is available from the new lot.", "Traffic", Priority.IMPORTANT, "Transport Department", "NEW", now.minusHours(2), now.minusHours(1), now.plusDays(1), true, "Panchavati North Parking", "North access road", "Panchavati", "North", "", "", 20.0080, 73.7920, false, "", "", "", "Panchavati", false, "", "", "", false, false));
        ITEMS.add(item("water-update", "Drinking Water Point Update", "A new verified drinking-water point is active near Seva Camp.", "Free drinking water is available beside the Seva Camp help desk during operating hours.", "General", Priority.NORMAL, "Ghat Management", "UPDATED", now.minusHours(3), now.minusMinutes(50), now.plusDays(2), true, "Seva Camp Water Point", "Beside the help desk", "Godavari Zone", "Sector A", "Seva Camp", "", 20.0052, 73.7888, false, "", "", "", "Sector A", false, "", "", "", false, false));
        ITEMS.add(item("expired-gate", "Gate 2 Temporarily Closed", "Gate 2 was closed during the previous crowd window.", "This advisory has ended. Gate access is now managed through the standard operating plan.", "Police / Security", Priority.IMPORTANT, "Nashik Police", "ENDED", now.minusDays(1), now.minusDays(1), now.minusHours(2), true, "Gate 2", "Ram Ghat approach", "Panchavati", "Gate 2", "", "Ram Ghat", 20.0061, 73.7896, false, "", "", "", "Ram Ghat", false, "", "", "", false, false));
    }
    private AnnouncementDemoStore() { }
    private static Announcement item(String id, String title, String shortD, String fullD, String category, Priority priority, String department, String status, LocalDateTime published, LocalDateTime updated, LocalDateTime valid, boolean hasLocation, String location, String address, String zone, String sector, String camp, String ghat, double lat, double lon, boolean changed, String oldLocation, String newLocation, String reason, String affectedArea, boolean required, String instruction, String alternativeLocation, String alternativeRoute, boolean dashboard, boolean emergency) { return new Announcement(id,title,shortD,fullD,category,priority,department,status,published,updated,valid,hasLocation,location,address,zone,sector,camp,ghat,lat,lon,changed,oldLocation,newLocation,reason,affectedArea,required,instruction,alternativeLocation,alternativeRoute,dashboard,emergency); }
    public static synchronized List<Announcement> all() { return ITEMS.stream().sorted(Comparator.comparingInt((Announcement a)->a.priority().ordinal()).thenComparing(Announcement::lastUpdated, Comparator.reverseOrder())).toList(); }
    public static synchronized void publish(Announcement item) { ITEMS.removeIf(a->a.id().equals(item.id())); ITEMS.add(item); }
    public static synchronized void remove(String id) { ITEMS.removeIf(a->a.id().equals(id)); READ.remove(id); BOOKMARKED.remove(id); }
    public static synchronized void archive(String id) { ITEMS.replaceAll(a -> a.id().equals(id) ? withStatus(a, "ENDED") : a); }
    public static synchronized Announcement duplicate(Announcement a) { Announcement copy = new Announcement(UUID.randomUUID().toString(), a.title()+" (Copy)", a.shortDescription(), a.fullDescription(), a.category(), a.priority(), a.department(), "DRAFT", LocalDateTime.now(), LocalDateTime.now(), a.validUntil(), a.hasLocation(), a.locationName(), a.address(), a.zone(), a.sector(), a.camp(), a.ghat(), a.latitude(), a.longitude(), a.locationChange(), a.previousLocation(), a.newLocation(), a.changeReason(), a.affectedArea(), a.actionRequired(), a.actionInstruction(), a.alternativeLocation(), a.alternativeRoute(), a.showDashboardAlert(), a.emergencyBanner()); ITEMS.add(copy); return copy; }
    public static synchronized void markRead(String id) { READ.add(id); }
    public static synchronized boolean isRead(String id) { return READ.contains(id); }
    public static synchronized long unreadCount() { return ITEMS.stream().filter(a->!READ.contains(a.id()) && !"ENDED".equals(a.status())).count(); }
    public static synchronized void toggleBookmark(String id) { if (!BOOKMARKED.add(id)) BOOKMARKED.remove(id); }
    public static synchronized boolean isBookmarked(String id) { return BOOKMARKED.contains(id); }
    public static Announcement draft(String title, String shortD, String fullD, String category, Priority priority, String department, String status, boolean hasLocation, String location, String address, String zone, String sector, String camp, String ghat, double lat, double lon, boolean changed, String oldLocation, String newLocation, String reason, String affectedArea, boolean required, String instruction, String alternative, String route, boolean dashboard, boolean emergency) { LocalDateTime now=LocalDateTime.now(); return new Announcement(UUID.randomUUID().toString(), title.isBlank()?"Untitled announcement":title, shortD, fullD, category, priority, department, status, now, now, now.plusHours(4), hasLocation, location, address, zone, sector, camp, ghat, lat, lon, changed, oldLocation, newLocation, reason, affectedArea, required, instruction, alternative, route, dashboard, emergency); }
    public static Announcement replaceContent(Announcement existing, Announcement draft) { return new Announcement(existing.id(), draft.title(), draft.shortDescription(), draft.fullDescription(), draft.category(), draft.priority(), draft.department(), draft.status(), existing.publishedAt(), LocalDateTime.now(), draft.validUntil(), draft.hasLocation(), draft.locationName(), draft.address(), draft.zone(), draft.sector(), draft.camp(), draft.ghat(), draft.latitude(), draft.longitude(), draft.locationChange(), draft.previousLocation(), draft.newLocation(), draft.changeReason(), draft.affectedArea(), draft.actionRequired(), draft.actionInstruction(), draft.alternativeLocation(), draft.alternativeRoute(), draft.showDashboardAlert(), draft.emergencyBanner()); }
    public static Announcement withStatus(Announcement a, String status) { return new Announcement(a.id(),a.title(),a.shortDescription(),a.fullDescription(),a.category(),a.priority(),a.department(),status,a.publishedAt(),LocalDateTime.now(),a.validUntil(),a.hasLocation(),a.locationName(),a.address(),a.zone(),a.sector(),a.camp(),a.ghat(),a.latitude(),a.longitude(),a.locationChange(),a.previousLocation(),a.newLocation(),a.changeReason(),a.affectedArea(),a.actionRequired(),a.actionInstruction(),a.alternativeLocation(),a.alternativeRoute(),a.showDashboardAlert(),a.emergencyBanner()); }
}
