package com.simhastha.view;

import com.simhastha.packages.*;
import com.simhastha.payment.*;
import java.math.BigDecimal;
import java.util.*;
import java.util.UUID;
import java.util.logging.Logger;
import java.util.function.Consumer;
import javafx.geometry.*;
import javafx.scene.Node;
import javafx.scene.CacheHint;
import javafx.scene.control.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.*;
import javafx.scene.shape.Rectangle;
import javafx.stage.Screen;
import javafx.stage.Stage;
import javafx.application.Platform;
import java.time.LocalDate;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javafx.util.StringConverter;

/** Part 2 in-memory customisation journey. It creates a Part 3 snapshot, never a booking/payment. */
public final class KumbhPackageCustomizationPage {
    private static final Logger LOGGER = Logger.getLogger(KumbhPackageCustomizationPage.class.getName());
    /** Temporary prototype-only branch. Set -Dkumbh.demoPayment=false when real checkout is enabled. */
    private static final boolean DEMO_PACKAGE_PAYMENT = Boolean.parseBoolean(System.getProperty("kumbh.demoPayment",
            System.getenv().getOrDefault("KUMBH_DEMO_PAYMENT", "true")));
    private static final List<String> STEPS = List.of("Travel", "Stay", "Meals", "Local Transport", "Kumbh Experience", "Nashik Sightseeing", "Puja & Add-ons", "Review");
    private static final String HOTEL_FALLBACK_IMAGE = Objects.requireNonNull(KumbhPackageCustomizationPage.class.getResource("/images/nashik-hotel-fallback.jpg")).toExternalForm();
    /* Local catalogue boundary: this can later be supplied by Admin/Firestore without changing the Stay UI. */
    private static final List<NashikHotel> NASHIK_HOTELS = List.of(
        new NashikHotel("ibis Nashik", "Satpur MIDC, Nashik", "Standard Queen Room", "Wi-Fi  •  Restaurant  •  Fitness centre", "4.1", 1500, "https://q-xx.bstatic.com/xdata/images/hotel/840x460/23143498.jpg?k=77481fb79ce39b1402e1a8fc48d56104ebe5a378d7ab2b286ca6416d1728e58a&o="),
        new NashikHotel("Ginger Nashik", "Satpur, Nashik", "Luxe Queen Room", "Wi-Fi  •  Qmin restaurant  •  Fitness centre", "3.9", 2000, "https://cdn.sanity.io/images/ocl5w36p/ihcl_prod/adf04af33aef13fe7af66cd6f165a03feff2c07b-3840x2104.jpg?w=980"),
        new NashikHotel("Hotel Rama Heritage", "Mumbai Naka, Nashik", "Deluxe AC Room", "Wi-Fi  •  Restaurant  •  Parking", "3.9", 2500, "https://cf.bstatic.com/xdata/images/hotel/max1024x768/477208638.jpg?k=4f8301a4d563ca0c593c508c4aa5ca61467b5becf6740f81a0bd861833ebe01d&o="),
        new NashikHotel("The Gateway Hotel Ambad Nashik", "Ambad, Nashik", "Superior Garden View Room", "Pool  •  Spa  •  Restaurant", "4.4", 5500, "https://pix10.agoda.net/property/17855229/0/eb606dfa19f8b6394f8dd81ceadb8008.jpg?ce=0&s=1024x"),
        new NashikHotel("Radisson Blu Hotel & Spa Nashik", "Pathardi Phata, Nashik", "Premium Room", "Spa  •  Pool  •  Fitness centre", "4.5", 6500, "https://media.radissonhotels.net/image/radisson-blu-hotel-spa-nashik/exterior/16256-126780-m26046072.jpg"),
        new NashikHotel("Express Inn Nashik", "Mumbai-Agra Road, Nashik", "Executive Room", "Pool  •  Restaurant  •  Parking", "4.0", 4000, "https://d25wybtmjgh8lz.cloudfront.net/sites/default/files/property/img-mastheads/bomei_1.jpg")
    );
    private static final List<String> MEAL_CATEGORIES = List.of("All", "Vegetarian", "Pure Vegetarian", "Maharashtrian", "Non-Veg", "North Indian", "Jain");
    private static final List<KumbhExperience> KUMBH_EXPERIENCES = List.of(
        new KumbhExperience("kumbh-assistance", "Kumbh Assistance", "Simhastha help and guidance during your package journey.", true, 0),
        new KumbhExperience("panchavati", "Panchavati", "Included Panchavati experience in your Kumbh journey.", true, 0),
        new KumbhExperience("ramkund-godavari-ghat", "Ramkund & Godavari Ghat Experience", "Guided visit around Ramkund and the Godavari Ghat area.", false, 500),
        new KumbhExperience("trimbakeshwar-kumbh", "Trimbakeshwar Kumbh Visit", "Package-assisted Trimbakeshwar visit.", false, 1200),
        new KumbhExperience("sadhugram-akhara", "Sadhugram / Akhara Experience", "Guided Kumbh cultural experience around permitted public areas.", false, 700),
        new KumbhExperience("evening-godavari-aarti", "Evening Godavari Aarti Experience", "Assisted evening visit for Godavari Aarti.", false, 400));
    private static final List<NashikSightseeing> NASHIK_SIGHTSEEING = List.of(
        new NashikSightseeing("sita-gufa-panchavati", "Sita Gufa & Panchavati", "Panchavati, Nashik", "Package visit to Sita Gufa and the Panchavati area.", "Approx. 2 hours", 300),
        new NashikSightseeing("muktidham-temple", "Muktidham Temple", "Nashik Road", "Package visit to Muktidham Temple.", "Approx. 2 hours", 300),
        new NashikSightseeing("pandavleni-caves", "Pandavleni Caves", "Nashik", "Package sightseeing visit to the Pandavleni Caves.", "Approx. 3 hours", 500),
        new NashikSightseeing("someshwar-godavari", "Someshwar Temple & Godavari Riverside", "Gangapur Road", "Package visit to Someshwar Temple and the Godavari riverside.", "Approx. 2 hours", 400),
        new NashikSightseeing("anjaneri-hills", "Anjaneri Hills Visit", "Trimbak Road", "Package sightseeing visit to Anjaneri Hills.", "Approx. 4 hours", 700),
        new NashikSightseeing("coin-museum-trimbak", "Coin Museum / Trimbak Route Stop", "Trimbak Road", "Package route stop at the Coin Museum / Trimbak route.", "Approx. 2 hours", 500));
    private static final List<PackageAddon> PACKAGE_ADDONS = List.of(
        new PackageAddon("sankalp-puja", "Sankalp Puja", "Simple package Sankalp Puja arrangement.", "Puja", 700),
        new PackageAddon("godavari-aarti-kit", "Godavari Aarti Puja Kit", "Basic puja kit for Godavari Aarti.", "Kit", 400),
        new PackageAddon("rudrabhishek-assistance", "Rudrabhishek Puja Assistance", "Package assistance for Rudrabhishek arrangements.", "Assistance", 1500),
        new PackageAddon("prasad-pack", "Prasad Pack", "Packaged prasad add-on for the traveller.", "Kit", 250),
        new PackageAddon("traditional-puja-kit", "Traditional Puja Kit", "Basic flowers, diya, kumkum and puja essentials.", "Kit", 350),
        new PackageAddon("senior-assistance", "Senior Citizen Assistance Add-on", "Additional on-ground assistance during package movement.", "Assistance", 500));
    /* Restaurant-only food catalogue; each entry is a verified Nashik dining outlet and a distinct outlet photo. */
    private static final List<NashikMealProvider> NASHIK_RESTAURANT_MEALS = List.of(
        new NashikMealProvider("Sadhana Chulivarchi Misal", "Gangapur-Satpur Link Road, Nashik", "Chulivarchi Misal Pav", "Wood-fired Maharashtrian misal with pav · breakfast or lunch", "Vegetarian · Maharashtrian", Set.of("Vegetarian", "Maharashtrian"), 350, "https://img.restaurantguru.com/rbe6-Sadhana-Chulivarchi-Misal-interior.jpg", List.of(section("Misal", item("Sadhana Chulivarchi Misal",120),item("Pav",10)))),
        new NashikMealProvider("Grape Embassy & Zatka Misal", "Makhmalabad Road, Nashik", "Misal Pav Meal Combo", "Fresh Nashik-style misal served under the grape-roof dining area", "Pure Vegetarian · Maharashtrian", Set.of("Vegetarian", "Pure Vegetarian", "Maharashtrian"), 450, "https://img.restaurantguru.com/reviews/small/w550/h367/632071.jpg", List.of(section("Menu Highlights",item("Nashik-style Misal Pav",null)))),
        new NashikMealProvider("Asian Wok & Grill", "Anandvalli, Gangapur Road, Nashik", "Vegetarian Asian Meal", "Asian vegetarian meal; Jain preparation is available on the menu", "Pure Vegetarian · Jain available", Set.of("Vegetarian", "Pure Vegetarian", "Jain"), 650, "https://dineout-media-assets.swiggy.com/swiggy/image/upload/fl_lossy%2Cf_auto%2Cq_auto/v1677566132/392c2d7702e4077a5ab4fc3518875b5c.jpg", List.of(section("Jain Options",item("Jain preparation (no onion or garlic)",null)),section("Menu Highlights",item("Vegetarian Asian dishes",null)))),
        new NashikMealProvider("Larive Kitchen and Cocktail", "College Road, Nashik", "Vegetarian North Indian Dinner", "Vegetarian fine dining with North Indian dishes · dinner", "Vegetarian · North Indian", Set.of("Vegetarian", "North Indian"), 1000, "https://www.lariverestaurants.com/_next/image?q=75&url=%2F_next%2Fstatic%2Fmedia%2Famb1.109cc6c6.jpg&w=3840", List.of(section("Menu Highlights",item("Vegetarian North Indian dishes",null),item("Plant-based specials",null)))),
        new NashikMealProvider("Aangan Family Restaurant", "Amrutdham, Nashik", "North Indian Non-Veg Meal", "North Indian family dining with vegetarian and non-vegetarian main-course choices · lunch or dinner", "Non-Veg · North Indian", Set.of("Vegetarian", "Non-Veg", "North Indian", "Maharashtrian"), 950, "https://aanganhospitality.in/lovable-assets/entrance.jpg", List.of(section("Starters",item("Achari Paneer Tikka",null),item("Angara Paneer Tikka",null)),section("Non-Veg",item("Non-vegetarian starters",null),item("Non-vegetarian main course",null)))),
        new NashikMealProvider("Hotel Swad NX Family Restaurant", "College Road, Nashik", "Maharashtrian Non-Veg Thali", "Maharashtrian family dining with chicken and mutton thalis", "Non-Veg · Maharashtrian", Set.of("Non-Veg", "Maharashtrian"), 900, "https://img3.restaurantguru.com/w550/h367/r22d-Hotel-Swad-NX-Family-Restaurant-interior-2025-05-1.jpg", List.of(section("Non-Veg Thali",item("Chicken Thali",450),item("Mutton Thali",550),item("Gavran Chicken Thali",550)))),
        new NashikMealProvider("Kokni Darbar", "Doodh Bazar, Nashik", "North Indian Non-Veg Dinner", "North Indian and non-vegetarian menu with biryani and main-course choices", "Non-Veg · North Indian", Set.of("Non-Veg", "North Indian"), 950, "https://b.zmtcdn.com/data/pictures/9/1600099/63aebcbb139a1a64961e30d1230b9f4e.jpg", List.of(section("Main Course",item("Mutton Handi",500),item("Chicken Garlic Dry",350)),section("Rice & Biryani",item("Chicken Biryani",220)))),
        new NashikMealProvider("Mughal Darbar", "Doodh Bazar, Nashik", "Mughlai Non-Veg Meal", "Mughlai and Chinese dining with kebabs, handis and biryani", "Non-Veg · North Indian", Set.of("Non-Veg", "North Indian"), 850, "https://files.yappe.in/place/full/mughal-darbar-1269164.webp", List.of(section("Menu Highlights",item("Kebabs",null),item("Handis",null),item("Biryani",null)))),
        new NashikMealProvider("Udupi Tadka's Sukh Sagar Pure Veg Restaurant", "Panchavati, Nashik", "Pure Veg North Indian Meal", "Pure vegetarian North Indian and Chinese dining", "Pure Vegetarian · North Indian", Set.of("Vegetarian", "Pure Vegetarian", "North Indian"), 700, "https://dineout-media-assets.swiggy.com/swiggy/image/upload/fl_lossy%2Cf_auto%2Cq_auto%2Cw_600%2Ch_468/v1693497266/5f482ea81029f640e1016c027c1be39c.webp", List.of(section("Breads",item("Roti",35),item("Chapati",25)),section("Starters",item("Chilli Paneer Dry",null),item("Veg Manchurian Dry",null)),section("Main Course",item("Paneer Butter Masala",null),item("Dal Tadka",null)))),
        new NashikMealProvider("Haji Darbar Restaurant", "Doodh Bazar, Nashik", "North Indian Mughlai Meal", "North Indian Mughlai and halal dining known for kebabs, curries and biryani", "Non-Veg · North Indian", Set.of("Non-Veg", "North Indian"), 1000, "https://b.zmtcdn.com/data/reviews_photos/cda/1add50b5b728f178f8e67d7c3d3e6cda_1483466960.jpg", List.of(section("Main Course",item("Mutton Nizami Handi",530)),section("Desserts",item("Shahi Kesar Phirni",100)),section("Menu Highlights",item("Tandoori chicken",null),item("Kebabs and biryani",null))))
    );
    private final KumbhPackage pkg; private final Consumer<Node> navigate; private final Runnable backToPackageDetails; private final Runnable openMyBookings; private final PackageCustomization state; private final PackageBookingRepository packageBookingRepository = new PackageBookingRepository();
    private enum ConnectMode { FLIGHT, TRAIN, BUS }
    private static final Map<TrainTravelClass,Integer> TRAIN_CHARGES=Map.of(TrainTravelClass.SL,900,TrainTravelClass.THREE_A,1500,TrainTravelClass.TWO_A,2100,TrainTravelClass.ONE_A,3200,TrainTravelClass.CC,1200,TrainTravelClass.TWO_S,600,TrainTravelClass.THREE_E,1300);
    private static final Map<BusType,Integer> BUS_CHARGES=Map.of(BusType.AC_SLEEPER,1400,BusType.NON_AC_SLEEPER,900,BusType.AC_SEATER,1000,BusType.VOLVO_AC,1600,BusType.SEMI_SLEEPER,1200);
    private final PackagePricingService pricing = new PackagePricingService(); private final FlightSearchService flightSearch = new FlightSearchService(); private int step; private String mealCategory="All"; private VBox body; private VBox summary; private HBox stepTabs; private boolean travelChooserOpen; private List<FlightOption> flightResults=List.of(); private String flightSearchMessage=""; private LocalDate selectedDepartureDate=LocalDate.now().plusDays(7); private LocalDate selectedTrainJourneyDate=LocalDate.now().plusDays(7); private ConnectMode connectMode=ConnectMode.FLIGHT; private String trainSearchMessage=""; private List<TrainJourney> trainResults=List.of(); private List<BusJourney> busResults=List.of(); private String busSearchMessage=""; private LocalDate selectedBusJourneyDate=LocalDate.now().plusDays(7); private NashikHotel hotelDetails; private double stayCatalogueScroll; private PackageCustomizationSnapshot travellerSnapshot; private PrimaryContact primaryContactDraft; private List<PackageTraveller> travellerDrafts=List.of(); private String emergencyContactDraft=""; private String assistanceNotesDraft=""; private PackageBookingDraft bookingDraft; private boolean travellerDetailsOpen; private boolean bookingSummaryOpen; private boolean demoPaymentSuccessOpen; private String demoPaymentReference=""; private boolean demoBookingSaving; private String demoBookingMessage=""; private PackageBooking confirmedPackageBooking; private PackageBooking pendingPackageBooking; private boolean bookingConfirmationOpen; private boolean paymentAttemptInProgress; private PaymentResult paymentResult;
    public KumbhPackageCustomizationPage(KumbhPackage pkg, Consumer<Node> navigate, Runnable backToPackageDetails) { this(pkg,navigate,backToPackageDetails,backToPackageDetails); }
    public KumbhPackageCustomizationPage(KumbhPackage pkg, Consumer<Node> navigate, Runnable backToPackageDetails, Runnable openMyBookings) { this.pkg=pkg; this.navigate=navigate; this.backToPackageDetails=backToPackageDetails; this.openMyBookings=openMyBookings; this.state=new PackageCustomization(pkg.id(), pkg.id()); initialiseDefaults(); }
    private void initialiseDefaults() { for (PackageOptionType type : List.of(PackageOptionType.TRAVEL,PackageOptionType.STAY,PackageOptionType.TRAVEL_CLASS,PackageOptionType.ROOM,PackageOptionType.MEAL,PackageOptionType.LOCAL_TRANSPORT)) PackageCustomizationOptions.options(pkg,type).stream().filter(PackageOption::included).findFirst().ifPresent(option->{state.select(option);if(type==PackageOptionType.LOCAL_TRANSPORT)state.selectedLocalTransport(localTransportSelection(option));}); KUMBH_EXPERIENCES.stream().filter(KumbhExperience::included).forEach(experience->state.selectKumbhExperience(experience.selection(pkg.id()))); }
    public Node create() { VBox header=new VBox(4,text("CUSTOMIZE YOUR JOURNEY","custom-eyebrow"),text(pkg.title(),"custom-title"),text(pkg.origin()+" → Nashik  •  "+pkg.duration()+"  •  Starting ₹"+String.format("%,d",pkg.price())+" / person","custom-meta")); header.getStyleClass().add("custom-header"); HBox main=new HBox(16); body=new VBox(14); summary=new VBox(10); summary.getStyleClass().add("custom-summary"); main.getChildren().addAll(body,summary); HBox.setHgrow(body,Priority.ALWAYS); VBox page=new VBox(14,header,stepper(),main); page.getStyleClass().add("package-page"); page.setPadding(new Insets(16,22,30,22)); render(); return page; }
    private Node stepper() { stepTabs=new HBox(6); stepTabs.getStyleClass().add("custom-stepper"); refreshStepper(); return stepTabs; }
    private void refreshStepper() { if(stepTabs==null)return; stepTabs.getChildren().clear(); for(int i=0;i<STEPS.size();i++){Label item=text((i+1)+". "+STEPS.get(i), i==step?"custom-step-active":"custom-step"); final int target=i; item.setOnMouseClicked(e->{hotelDetails=null;travellerDetailsOpen=false;bookingSummaryOpen=false;demoPaymentSuccessOpen=false;bookingConfirmationOpen=false;step=target;render();}); stepTabs.getChildren().add(item);} }
    private void render() { refreshStepper(); if(bookingConfirmationOpen)body.getChildren().setAll(bookingConfirmationPage());else if(demoPaymentSuccessOpen)body.getChildren().setAll(demoPaymentSuccessPage());else if(bookingSummaryOpen)body.getChildren().setAll(bookingSummaryShell());else if(travellerDetailsOpen)body.getChildren().setAll(travellerDetailsPage());else if(step==1&&hotelDetails!=null)body.getChildren().setAll(hotelDetailsStep());else body.getChildren().setAll(stepContent(), navigation()); updateSummary(); }
    private Node stepContent() { return switch(step) { case 0 -> travelStep(); case 1 -> stayStep(); case 2 -> mealsStep(); case 3 -> localTransportStep(); case 4 -> kumbhExperienceStep(); case 5 -> sightseeingStep(); case 6 -> pujaAddonsStep(); default -> review(); }; }
    private Node travelStep() {
        PackageTravelConfig config=PackageTravelConfig.fromTravelOptions(pkg.travelChoices(),pkg.origin());
        VBox out=new VBox(12,text("Choose Travel","custom-section-title"),text("Choose your journey preference. Airline schedules are live provider data; package flight charges are configured by Simhastha Connect.","custom-help"));
        if(config.selfTravelEnabled()) PackageCustomizationOptions.options(pkg,PackageOptionType.TRAVEL).stream().filter(option->option.label().equalsIgnoreCase("Self Travel")).findFirst().ifPresent(option->out.getChildren().add(optionCard(option,true)));
        if(config.simhasthaConnectEnabled()) {
            PackageOption connect=new PackageOption(pkg.id()+":TRAVEL:simhastha-connect",PackageOptionType.TRAVEL,"Simhastha Connect Travel","Book your journey through Simhastha Connect",0,false,false,false);
            boolean selected=connect.equals(state.selected(PackageOptionType.TRAVEL)); Button choose=new Button(selected?"Selected":"Choose Travel");choose.getStyleClass().add(selected?"custom-selected-button":"custom-option-button");choose.setOnAction(e->{state.select(connect);travelChooserOpen=true;render();});
            VBox copy=new VBox(3,text("Simhastha Connect Travel","custom-option-title"),text("Book your journey through Simhastha Connect","custom-help"));HBox card=new HBox(12,copy,spacer(),text("Package travel","custom-upgrade"),choose);card.setAlignment(Pos.CENTER_LEFT);card.getStyleClass().addAll("custom-option-card",selected?"custom-option-selected":"");out.getChildren().add(card);
            if(selected||travelChooserOpen) out.getChildren().add(flightSelection(config));
        }
        return out;
    }
    private Node flightSelection(PackageTravelConfig config) {
        VBox out=new VBox(10,text("Choose Travel Mode","custom-group-title"));
        Button flight=new Button("✈  Flight");flight.getStyleClass().add(connectMode==ConnectMode.FLIGHT?"custom-selected-button":"custom-option-button");flight.setDisable(!config.flightEnabled());flight.setOnAction(e->{connectMode=ConnectMode.FLIGHT;render();});
        Button train=new Button("Train");train.getStyleClass().add(connectMode==ConnectMode.TRAIN?"custom-selected-button":"custom-option-button");train.setOnAction(e->{connectMode=ConnectMode.TRAIN;render();});
        Button bus=new Button("Bus");bus.getStyleClass().add(connectMode==ConnectMode.BUS?"custom-selected-button":"custom-option-button");bus.setOnAction(e->{connectMode=ConnectMode.BUS;render();});
        HBox modes=new HBox(8,flight,train,bus);out.getChildren().add(modes);
        if(connectMode==ConnectMode.TRAIN){out.getChildren().add(trainSelection());return out;}
        if(connectMode==ConnectMode.BUS){out.getChildren().add(busSelection());return out;}
        if(!config.flightEnabled()){out.getChildren().add(text("Flight is currently disabled by the package administrator.","custom-help"));return out;}
        TextField from=new TextField(config.defaultOriginAirport()); TextField to=new TextField(config.destinationAirport()); DatePicker date=departureDatePicker(); Spinner<Integer> travellers=new Spinner<>(1,9,1); ComboBox<CabinClass> cabin=new ComboBox<>();cabin.getStyleClass().add("custom-travel-combo");cabin.getItems().addAll(config.allowedCabins());cabin.setValue(config.allowedCabins().contains(CabinClass.ECONOMY)?CabinClass.ECONOMY:config.allowedCabins().iterator().next());
        GridPane search=new GridPane();search.setHgap(8);search.setVgap(8);search.add(text("From","custom-group-title"),0,0);search.add(text("To","custom-group-title"),1,0);search.add(text("Departure Date","custom-group-title"),2,0);search.add(text("Travellers","custom-group-title"),3,0);search.add(text("Cabin Class","custom-group-title"),4,0);search.add(from,0,1);search.add(to,1,1);search.add(date,2,1);search.add(travellers,3,1);search.add(cabin,4,1);
        Button submit=new Button("Search Flights");submit.getStyleClass().add("package-search-button");Label message=text(flightSearchMessage,"custom-help");submit.setOnAction(e->{ LocalDate departure=commitDepartureDate(date); if(departure==null){message.setText("Enter a valid departure date as dd/MM/yyyy.");return;} searchFlights(new FlightSearchRequest(from.getText().trim().toUpperCase(Locale.ROOT),to.getText().trim().toUpperCase(Locale.ROOT),departure,travellers.getValue(),cabin.getValue()),message); });out.getChildren().addAll(search,submit,message);
        if(!flightResults.isEmpty()){out.getChildren().add(text("Live / current flight information","custom-group-title"));flightResults.forEach(option->out.getChildren().add(flightCard(option,config,cabin.getValue())));}
        out.getChildren().add(text("Selecting a flight adds the configured package charge only. Airline ticket issuance remains pending provider confirmation.","custom-help"));return out;
    }
    private void searchFlights(FlightSearchRequest request,Label message) { flightResults=List.of();flightSearchMessage="Searching live Aviationstack flight information…";render();flightSearch.searchAsync(request).whenComplete((results,error)->Platform.runLater(()->{if(error!=null){flightSearchMessage=error.getCause()==null?"Unable to load live flight information.":error.getCause().getMessage();flightResults=List.of();}else{flightResults=results.stream().filter(flight->request.originAirport().equalsIgnoreCase(flight.departure().airportCode())&&request.destinationAirport().equalsIgnoreCase(flight.arrival().airportCode())).toList();flightSearchMessage=flightResults.isEmpty()?"No live flights found for "+request.originAirport()+" → "+request.destinationAirport()+".":flightResults.size()+" live / current flight result(s) returned by Aviationstack.";}render();})); }
    private DatePicker departureDatePicker() { DatePicker picker=new DatePicker(selectedDepartureDate);DateTimeFormatter format=DateTimeFormatter.ofPattern("dd/MM/yyyy");picker.setEditable(true);picker.setPromptText("dd/MM/yyyy");picker.setConverter(new StringConverter<>() { @Override public String toString(LocalDate value) { return value == null ? "" : format.format(value); } @Override public LocalDate fromString(String value) { return value == null || value.isBlank() ? null : LocalDate.parse(value.trim(),format); } });picker.valueProperty().addListener((observable,oldDate,newDate)->{if(newDate!=null)selectedDepartureDate=newDate;});return picker; }
    private LocalDate commitDepartureDate(DatePicker picker) { try { LocalDate value=picker.getConverter().fromString(picker.getEditor().getText());if(value!=null){picker.setValue(value);selectedDepartureDate=value;}return value; } catch(DateTimeParseException exception) { return null; } }
    private Node trainSelection() {
        VBox out=new VBox(10,text("Search Trains","custom-group-title"));TrainSearchRequest saved=state.trainSearch();
        TextField from=new TextField(saved==null?"":saved.fromStation());from.setPromptText("Station name or code (e.g. AWB)");
        TextField to=new TextField(saved==null?"NK":saved.toStation());to.setPromptText("Station name or code (e.g. NK)");
        DatePicker date=trainDatePicker();Spinner<Integer> travellers=new Spinner<>(1,9,saved==null?1:Math.max(1,saved.travellers()));ComboBox<TrainTravelClass> travelClass=new ComboBox<>();travelClass.getStyleClass().add("custom-travel-combo");travelClass.getItems().addAll(TrainTravelClass.values());travelClass.setValue(saved==null?TrainTravelClass.SL:saved.travelClass());
        GridPane form=new GridPane();form.setHgap(8);form.setVgap(8);form.add(text("From Station","custom-group-title"),0,0);form.add(text("To Station","custom-group-title"),1,0);form.add(text("Journey Date","custom-group-title"),2,0);form.add(text("Travellers","custom-group-title"),3,0);form.add(text("Travel Class","custom-group-title"),4,0);form.add(from,0,1);form.add(to,1,1);form.add(date,2,1);form.add(travellers,3,1);form.add(travelClass,4,1);
        Label message=text(trainSearchMessage,"custom-help");Button search=new Button("Search Trains");search.getStyleClass().add("package-search-button");search.setOnAction(e->{LocalDate journey=commitTrainDate(date);String origin=station(from.getText());String destination=station(to.getText());if(origin.isBlank()){trainSearchMessage="Enter a From station name or code.";}else if(destination.isBlank()){trainSearchMessage="Enter a To station name or code.";}else if(origin.equalsIgnoreCase(destination)){trainSearchMessage="From and To stations must be different.";}else if(journey==null){trainSearchMessage="Enter a valid journey date as dd/MM/yyyy.";}else if(travellers.getValue()==null||travellers.getValue()<1){trainSearchMessage="Travellers must be at least 1.";}else if(travelClass.getValue()==null){trainSearchMessage="Select a travel class.";}else{TrainSearchRequest request=new TrainSearchRequest(origin,destination,journey,travellers.getValue(),travelClass.getValue());state.trainSearch(request);searchTrains(request);}render();});out.getChildren().addAll(form,search,message);if(!trainResults.isEmpty()){out.getChildren().add(text("Train schedules","custom-group-title"));trainResults.forEach(train->out.getChildren().add(trainCard(train,saved)));}out.getChildren().add(text("Simhastha Connect train charges are package charges, not railway fares or ticket confirmation.","custom-help"));return out;
    }
    private void searchTrains(TrainSearchRequest request) { trainResults=demoTrains(request);trainSearchMessage=trainResults.isEmpty()?"No trains found for "+request.fromStation()+" → "+request.toStation()+".":trainResults.size()+" matching train schedule(s)."; }
    private Node trainCard(TrainJourney train,TrainSearchRequest request) { boolean classSupported=train.availableClasses().contains(request.travelClass());int charge=TRAIN_CHARGES.get(request.travelClass());PackageOption option=new PackageOption(pkg.id()+":TRAVEL_CLASS:train:"+train.trainNumber()+":"+request.travelClass().name(),PackageOptionType.TRAVEL_CLASS,"Train — "+request.travelClass().label()+" · "+train.trainName()+" "+train.trainNumber(),"Simhastha Connect Train Charge",charge,false,false,false);boolean selected=option.equals(state.selected(PackageOptionType.TRAVEL_CLASS));VBox info=new VBox(3,text(train.trainName()+"\n"+train.trainNumber(),"custom-option-title"),text(train.fromStationCode()+" "+train.fromStationName()+"  "+train.departureTime()+"  →  "+train.toStationCode()+" "+train.toStationName()+"  "+train.arrivalTime(),"custom-help"),text("Duration: "+train.duration()+"  •  Runs: "+train.runningDays(),"custom-help"),text("Classes: "+train.availableClasses().stream().map(TrainTravelClass::label).collect(java.util.stream.Collectors.joining(", ")),"custom-meal-diet"));HBox.setHgrow(info,Priority.ALWAYS);Button select=new Button(selected?"Selected":"Select Train");select.getStyleClass().add(selected?"custom-selected-button":"custom-option-button");select.setDisable(!classSupported);select.setOnAction(e->{state.activateTravel(option);state.selectedTrain(train);render();});Button details=new Button("View Details");details.getStyleClass().add("custom-hotel-details-button");details.setOnAction(e->trainDetails(train,request,charge));VBox actions=new VBox(5,text("₹"+String.format("%,d",charge)+"\nSimhastha Connect Train Charge","custom-hotel-price"),select,details);actions.setAlignment(Pos.CENTER_RIGHT);HBox card=new HBox(12,info,actions);card.setAlignment(Pos.CENTER_LEFT);card.getStyleClass().addAll("custom-option-card",selected?"custom-option-selected":"");return card; }
    private void trainDetails(TrainJourney train,TrainSearchRequest request,int charge) { Alert alert=new Alert(Alert.AlertType.INFORMATION);alert.setTitle("Train details");alert.setHeaderText(train.trainName()+" "+train.trainNumber());alert.setContentText(train.fromStationName()+" ("+train.fromStationCode()+") → "+train.toStationName()+" ("+train.toStationCode()+")\n"+train.departureTime()+" → "+train.arrivalTime()+"  •  "+train.duration()+"\nClass preference: "+request.travelClass().label()+"\nRunning days: "+train.runningDays()+"\n\nSimhastha Connect Train Charge: ₹"+String.format("%,d",charge)+"\nNo ticket, berth, PNR, fare, or availability is confirmed.");alert.showAndWait(); }
    private static List<TrainJourney> demoTrains(TrainSearchRequest request) { String from=request.fromStation(),to=request.toStation();List<TrainJourney> all=List.of(train("17057","DEVAGIRI EXPRESS","AWB","Chhatrapati Sambhajinagar","NK","Nashik Road","22:30","03:40","5h 10m",List.of(TrainTravelClass.SL,TrainTravelClass.THREE_A,TrainTravelClass.TWO_A)),train("17617","TAPOVAN EXPRESS","AWB","Chhatrapati Sambhajinagar","NK","Nashik Road","06:20","11:45","5h 25m",List.of(TrainTravelClass.SL,TrainTravelClass.THREE_A)),train("12109","PANCHAVATI EXPRESS","CSMT","Mumbai CSMT","NK","Nashik Road","18:15","21:25","3h 10m",List.of(TrainTravelClass.CC,TrainTravelClass.TWO_S,TrainTravelClass.THREE_A)),train("11039","MAHARASHTRA EXPRESS","PUNE","Pune Junction","NK","Nashik Road","23:20","05:30","6h 10m",List.of(TrainTravelClass.SL,TrainTravelClass.THREE_A,TrainTravelClass.TWO_A)),train("12131","DADAR SAI NAGAR EXPRESS","MMR","Manmad Junction","NK","Nashik Road","14:10","15:25","1h 15m",List.of(TrainTravelClass.SL,TrainTravelClass.THREE_A)),train("12424","RAJDHANI EXPRESS","NDLS","New Delhi","NK","Nashik Road","16:55","10:35","17h 40m",List.of(TrainTravelClass.ONE_A,TrainTravelClass.TWO_A,TrainTravelClass.THREE_A)),train("17058","DEVAGIRI EXPRESS","NK","Nashik Road","AWB","Chhatrapati Sambhajinagar","23:05","04:20","5h 15m",List.of(TrainTravelClass.SL,TrainTravelClass.THREE_A,TrainTravelClass.TWO_A)));return all.stream().filter(train->train.fromStationCode().equalsIgnoreCase(from)&&train.toStationCode().equalsIgnoreCase(to)).toList(); }
    private static TrainJourney train(String number,String name,String fromCode,String fromName,String toCode,String toName,String departure,String arrival,String duration,List<TrainTravelClass> classes){return new TrainJourney(number,name,fromCode,fromName,toCode,toName,departure,arrival,duration,null,classes,"Daily","Demo schedule",null,"Internal curated demo");}
    private DatePicker trainDatePicker() { DatePicker picker=new DatePicker(selectedTrainJourneyDate);DateTimeFormatter format=DateTimeFormatter.ofPattern("dd/MM/yyyy");picker.setEditable(true);picker.setPromptText("dd/MM/yyyy");picker.setConverter(new StringConverter<>() { @Override public String toString(LocalDate value) { return value == null ? "" : format.format(value); } @Override public LocalDate fromString(String value) { return value == null || value.isBlank() ? null : LocalDate.parse(value.trim(),format); } });picker.valueProperty().addListener((observable,oldDate,newDate)->{if(newDate!=null)selectedTrainJourneyDate=newDate;});return picker; }
    private LocalDate commitTrainDate(DatePicker picker) { try { LocalDate value=picker.getConverter().fromString(picker.getEditor().getText());if(value!=null){picker.setValue(value);selectedTrainJourneyDate=value;}return value; } catch(DateTimeParseException exception) { return null; } }
    private String station(String value) { return value == null ? "" : value.trim().replaceAll("\\s+"," ").toUpperCase(Locale.ROOT); }
    private Node busSelection() { VBox out=new VBox(10,text("Search Buses","custom-group-title"));TextField from=new TextField();from.setPromptText("From City");TextField to=new TextField("Nashik");to.setPromptText("To City");DatePicker date=busDatePicker();Spinner<Integer> travellers=new Spinner<>(1,9,1);ComboBox<BusType> type=new ComboBox<>();type.getStyleClass().add("custom-travel-combo");type.getItems().addAll(BusType.values());type.setValue(BusType.AC_SLEEPER);GridPane form=new GridPane();form.setHgap(8);form.setVgap(8);form.add(text("From City","custom-group-title"),0,0);form.add(text("To City","custom-group-title"),1,0);form.add(text("Journey Date","custom-group-title"),2,0);form.add(text("Travellers","custom-group-title"),3,0);form.add(text("Bus Type","custom-group-title"),4,0);form.add(from,0,1);form.add(to,1,1);form.add(date,2,1);form.add(travellers,3,1);form.add(type,4,1);Label message=text(busSearchMessage,"custom-help");Button search=new Button("Search Buses");search.getStyleClass().add("package-search-button");search.setOnAction(e->{LocalDate journey=commitBusDate(date);String origin=city(from.getText()),destination=city(to.getText());if(origin.isBlank()||destination.isBlank())busSearchMessage="Enter both From and To cities.";else if(origin.equals(destination))busSearchMessage="From and To cities must be different.";else if(journey==null)busSearchMessage="Enter a valid journey date as dd/MM/yyyy.";else{busResults=demoBuses(origin,destination,journey,type.getValue());busSearchMessage=busResults.isEmpty()?"No buses found for "+origin+" → "+destination+".":busResults.size()+" matching bus schedule(s).";}render();});out.getChildren().addAll(form,search,message);if(!busResults.isEmpty()){out.getChildren().add(text("Bus schedules","custom-group-title"));busResults.forEach(bus->out.getChildren().add(busCard(bus)));}out.getChildren().add(text("Simhastha Connect Bus Charges are package charges, not live operator fares or ticket confirmation.","custom-help"));return out; }
    private Node busCard(BusJourney bus) { int charge=BUS_CHARGES.get(bus.type());String operator=displayBusName(bus.operator());PackageOption option=new PackageOption(pkg.id()+":TRAVEL_CLASS:bus:"+bus.operator().replaceAll("\\W+","-")+":"+bus.type().name(),PackageOptionType.TRAVEL_CLASS,"Bus — "+bus.type().label()+" · "+operator,"Simhastha Connect Bus Charge",charge,false,false,false);boolean selected=option.equals(state.selected(PackageOptionType.TRAVEL_CLASS));VBox info=new VBox(3,text(operator+"\n"+bus.type().label(),"custom-option-title"),text(bus.fromCity()+"  "+bus.departureTime()+"  →  "+bus.toCity()+"  "+bus.arrivalTime(),"custom-help"),text("Duration: "+bus.duration()+"  •  Board: "+bus.boardingPoint()+"  •  Drop: "+bus.dropPoint(),"custom-help"),text(displayBusSeats(bus.demoSeats()),"custom-meal-diet"));HBox.setHgrow(info,Priority.ALWAYS);Button select=new Button(selected?"Selected":"Select Bus");select.getStyleClass().add(selected?"custom-selected-button":"custom-option-button");select.setOnAction(e->{state.activateTravel(option);state.selectedBus(bus);render();});Button details=new Button("View Details");details.getStyleClass().add("custom-hotel-details-button");details.setOnAction(e->{Alert alert=new Alert(Alert.AlertType.INFORMATION);alert.setTitle("Bus details");alert.setHeaderText(operator+" — "+bus.type().label());alert.setContentText(bus.fromCity()+" → "+bus.toCity()+"\n"+bus.departureTime()+" → "+bus.arrivalTime()+"  •  "+bus.duration()+"\nBoarding: "+bus.boardingPoint()+"\nDrop: "+bus.dropPoint()+"\n\nSimhastha Connect Bus Charge: ₹"+String.format("%,d",charge)+"\nNo ticket, seat, fare, or availability is confirmed.");alert.showAndWait();});VBox actions=new VBox(5,text("₹"+String.format("%,d",charge)+"\nSimhastha Connect Bus Charge","custom-hotel-price"),select,details);actions.setAlignment(Pos.CENTER_RIGHT);HBox card=new HBox(12,info,actions);card.setAlignment(Pos.CENTER_LEFT);card.getStyleClass().addAll("custom-option-card",selected?"custom-option-selected":"");return card; }
    private static List<BusJourney> demoBuses(String from,String to,LocalDate date,BusType selectedType){List<BusJourney> all=List.of(bus("Simhastha Connect Demo Coach","Chhatrapati Sambhajinagar","Nashik","22:00","03:30","5h 30m","Central Bus Stand","CBS Nashik","Demo seats available",BusType.AC_SLEEPER,date),bus("Maharashtra Pilgrim Demo","Chhatrapati Sambhajinagar","Nashik","23:15","04:55","5h 40m","CIDCO Bus Stand","CBS Nashik","Demo seats available",BusType.SEMI_SLEEPER,date),bus("Mumbai Nashik Demo Travels","Mumbai","Nashik","18:30","22:45","4h 15m","Dadar East","Mumbai Naka","Demo seats available",BusType.VOLVO_AC,date),bus("Pune Nashik Demo Express","Pune","Nashik","19:00","23:15","4h 15m","Swargate","Mumbai Naka","Demo seats available",BusType.AC_SEATER,date),bus("Shirdi Nashik Demo Shuttle","Shirdi","Nashik","17:40","20:15","2h 35m","Shirdi Bus Stand","CBS Nashik","Demo seats available",BusType.NON_AC_SLEEPER,date),bus("Nashik Aurangabad Demo","Nashik","Chhatrapati Sambhajinagar","22:15","03:45","5h 30m","CBS Nashik","Central Bus Stand","Demo seats available",BusType.AC_SLEEPER,date));return all.stream().filter(bus->bus.fromCity().equalsIgnoreCase(from)&&bus.toCity().equalsIgnoreCase(to)&&bus.type()==selectedType).toList();}
    private static BusJourney bus(String operator,String from,String to,String departure,String arrival,String duration,String boarding,String drop,String seats,BusType type,LocalDate date){return new BusJourney(operator,type,from,to,departure,arrival,duration,boarding,drop,seats,date);}
    private DatePicker busDatePicker(){DatePicker picker=new DatePicker(selectedBusJourneyDate);DateTimeFormatter format=DateTimeFormatter.ofPattern("dd/MM/yyyy");picker.setEditable(true);picker.setConverter(new StringConverter<>(){@Override public String toString(LocalDate value){return value==null?"":format.format(value);}@Override public LocalDate fromString(String value){return value==null||value.isBlank()?null:LocalDate.parse(value.trim(),format);}});picker.valueProperty().addListener((o,a,value)->{if(value!=null)selectedBusJourneyDate=value;});return picker;}
    private LocalDate commitBusDate(DatePicker picker){try{LocalDate value=picker.getConverter().fromString(picker.getEditor().getText());if(value!=null){picker.setValue(value);selectedBusJourneyDate=value;}return value;}catch(DateTimeParseException exception){return null;}}
    private String city(String value){return value==null?"":value.trim().replaceAll("\\s+"," ");}
    private String displayBusName(String value){return value==null?"":value.replaceAll("(?i)\\s*demo\\s*", " ").replaceAll("\\s+", " ").trim();}
    private String displayBusSeats(String value){return value==null?"":value.replaceAll("(?i)demo\\s*", "").trim();}
    private Node flightCard(FlightOption flight,PackageTravelConfig config,CabinClass cabin) { int charge=config.charge(cabin);PackageOption option=new PackageOption(pkg.id()+":TRAVEL_CLASS:flight:"+flight.flightNumber()+":"+cabin.name(),PackageOptionType.TRAVEL_CLASS,"Flight — "+cabin.label()+" · "+flight.airline()+" "+flight.flightNumber(),"Package flight charge; ticketing remains provider confirmation.",charge,false,false,false);boolean selected=option.equals(state.selected(PackageOptionType.TRAVEL_CLASS));Label airline=text("✈  "+flight.airline()+"\n"+flight.flightNumber(),"custom-option-title");VBox route=new VBox(3,text(flight.departure().airportCode()+"  "+flight.departure().city()+"  "+flight.departure().scheduledTime(),"custom-help"),text("→  "+flight.duration()+"  →","custom-hotel-locality"),text(flight.arrival().airportCode()+"  "+flight.arrival().city()+"  "+flight.arrival().scheduledTime(),"custom-help"),text("Status: "+flight.status()+"  •  "+cabin.label(),"custom-meal-diet"));HBox.setHgrow(route,Priority.ALWAYS);Button select=new Button(selected?"Selected":"Select Flight");select.getStyleClass().add(selected?"custom-selected-button":"custom-option-button");select.setOnAction(e->{state.activateTravel(option);state.selectedFlight(flight);render();});Button details=new Button("View Details");details.getStyleClass().add("custom-hotel-details-button");details.setOnAction(e->{Alert alert=new Alert(Alert.AlertType.INFORMATION);alert.setTitle("Flight schedule");alert.setHeaderText(flight.airline()+" "+flight.flightNumber());alert.setContentText("Departure: "+flight.departure().scheduledTime()+"\nArrival: "+flight.arrival().scheduledTime()+"\nStatus: "+flight.status()+"\n\nFlight reservation/request pending provider confirmation.");alert.showAndWait();});VBox actions=new VBox(5,text("+ ₹"+String.format("%,d",charge)+"\nper traveller","custom-hotel-price"),select,details);actions.setAlignment(Pos.CENTER_RIGHT);HBox card=new HBox(12,airline,route,actions);card.setAlignment(Pos.CENTER_LEFT);card.getStyleClass().addAll("custom-option-card",selected?"custom-option-selected":"");return card; }
    private Node optionStep(String title, String help, List<PackageOptionType> types, boolean single) { VBox out=new VBox(12,text(title,"custom-section-title"),text(help,"custom-help")); boolean any=false; for(PackageOptionType type:types){List<PackageOption> opts=PackageCustomizationOptions.options(pkg,type); if(opts.isEmpty())continue;any=true;out.getChildren().add(text(label(type),"custom-group-title")); for(PackageOption option:opts)out.getChildren().add(optionCard(option,single));} if(!any)out.getChildren().add(text("No additional choices are configured for this package.","custom-help")); return out; }
    private Node localTransportStep() { VBox out=new VBox(12,text("Local Transport & Pickup","custom-section-title"),text("Select local movement and pickup preference.","custom-help"),text("Local transport","custom-group-title")); PackageCustomizationOptions.options(pkg,PackageOptionType.LOCAL_TRANSPORT).forEach(option->out.getChildren().add(localTransportCard(option))); return out; }
    private Node localTransportCard(PackageOption option) { boolean selected=option.equals(state.selected(PackageOptionType.LOCAL_TRANSPORT)); String price=option.included()?"Included":"+ ₹"+String.format("%,d",option.price()); Button action=new Button(selected?"Selected":"Select");action.getStyleClass().add(selected?"custom-selected-button":"custom-option-button");action.setOnAction(e->{state.select(option);state.selectedLocalTransport(localTransportSelection(option));render();}); VBox copy=new VBox(3,text(option.label(),"custom-option-title"),text(option.description(),"custom-help")); HBox row=new HBox(12,copy,spacer(),text(price,option.included()?"custom-included":"custom-upgrade"),action);row.setAlignment(Pos.CENTER_LEFT);row.getStyleClass().addAll("custom-option-card",selected?"custom-option-selected":"");return row; }
    private LocalTransportSelection localTransportSelection(PackageOption option) { String id=option.id(); if(id.endsWith(":private-sedan"))return new LocalTransportSelection(id,"Private Sedan","Private local transport",option.price()); if(id.endsWith(":suv"))return new LocalTransportSelection(id,"SUV","Family local transport",option.price()); return new LocalTransportSelection(id,"Shared Shuttle","Included",0); }
    private Node kumbhExperienceStep() { VBox out=new VBox(12,text("Kumbh Experience","custom-section-title"),text("Included Kumbh assistance remains active. Add any optional experiences that suit your journey.","custom-help"),text("Included experiences","custom-group-title")); KUMBH_EXPERIENCES.stream().filter(KumbhExperience::included).forEach(experience->out.getChildren().add(kumbhExperienceCard(experience))); out.getChildren().add(text("Optional Kumbh experiences","custom-group-title")); KUMBH_EXPERIENCES.stream().filter(experience->!experience.included()).forEach(experience->out.getChildren().add(kumbhExperienceCard(experience))); return out; }
    private Node kumbhExperienceCard(KumbhExperience experience) { PackageOption option=experience.option(pkg.id()); boolean selected=experience.included()||state.selected(option); Button action=new Button(experience.included()?"Selected":selected?"Selected":"Select");action.getStyleClass().add(selected?"custom-selected-button":"custom-option-button");action.setDisable(experience.included());action.setOnAction(e->{boolean nowSelected=!state.selected(option);state.toggle(option,nowSelected);if(nowSelected)state.selectKumbhExperience(experience.selection(pkg.id()));else state.removeKumbhExperience(experience.id());render();}); VBox copy=new VBox(3,text(experience.name(),"custom-option-title"),text(experience.description(),"custom-help"));String price=experience.included()?"Included":"+ ₹"+String.format("%,d",experience.upgrade())+" per traveller";HBox row=new HBox(12,copy,spacer(),text(price,experience.included()?"custom-included":"custom-upgrade"),action);row.setAlignment(Pos.CENTER_LEFT);row.getStyleClass().addAll("custom-option-card",selected?"custom-option-selected":"");return row; }
    private Node sightseeingStep() { VBox out=new VBox(12,text("Customize Nashik Sightseeing","custom-section-title"),text("Select any optional sightseeing stops for your package journey. Charges shown are package sightseeing charges.","custom-help")); NASHIK_SIGHTSEEING.forEach(sightseeing->out.getChildren().add(sightseeingCard(sightseeing))); return out; }
    private Node sightseeingCard(NashikSightseeing sightseeing) { PackageOption option=sightseeing.option(pkg.id()); boolean selected=state.selected(option);Button action=new Button(selected?"Selected":"Select");action.getStyleClass().add(selected?"custom-selected-button":"custom-option-button");action.setOnAction(e->{boolean nowSelected=!state.selected(option);state.toggle(option,nowSelected);if(nowSelected)state.selectSightseeing(sightseeing.selection(pkg.id()));else state.removeSightseeing(sightseeing.id());render();});VBox copy=new VBox(3,text(sightseeing.name(),"custom-option-title"),text(sightseeing.location()+"  •  "+sightseeing.duration(),"custom-hotel-locality"),text(sightseeing.description(),"custom-help"));HBox row=new HBox(12,copy,spacer(),text("+ ₹"+String.format("%,d",sightseeing.packageCharge())+"\nPackage sightseeing charge","custom-upgrade"),action);row.setAlignment(Pos.CENTER_LEFT);row.getStyleClass().addAll("custom-option-card",selected?"custom-option-selected":"");return row; }
    private Node pujaAddonsStep() { VBox out=new VBox(12,text("Puja & Add-ons","custom-section-title"),text("Optional package add-ons only. These are not Puja Services bookings, reservations, or payment confirmations.","custom-help")); PACKAGE_ADDONS.forEach(addon->out.getChildren().add(packageAddonCard(addon))); return out; }
    private Node packageAddonCard(PackageAddon addon) { PackageOption option=addon.option(pkg.id()); boolean selected=state.selected(option);Button action=new Button(selected?"Selected":"Select");action.getStyleClass().add(selected?"custom-selected-button":"custom-option-button");action.setOnAction(e->{boolean nowSelected=!state.selected(option);state.toggle(option,nowSelected);if(nowSelected)state.selectPackageAddon(addon.selection(pkg.id()));else state.removePackageAddon(addon.id());render();});VBox copy=new VBox(3,text(addon.name(),"custom-option-title"),text(addon.category(),"custom-hotel-locality"),text(addon.description(),"custom-help"));HBox row=new HBox(12,copy,spacer(),text("+ ₹"+String.format("%,d",addon.upgrade())+"\nPackage add-on charge","custom-upgrade"),action);row.setAlignment(Pos.CENTER_LEFT);row.getStyleClass().addAll("custom-option-card",selected?"custom-option-selected":"");return row; }
    private Node stayStep() { VBox out=new VBox(12,text("Choose Your Stay","custom-section-title"),text("Choose your included stay or upgrade to a verified Nashik hotel. One stay option is selected at a time.","custom-help")); List<PackageOption> stays=PackageCustomizationOptions.options(pkg,PackageOptionType.STAY); out.getChildren().add(text("Included stay","custom-group-title")); if(stays.isEmpty())out.getChildren().add(text("No included stay is configured for this package.","custom-help"));else stays.forEach(o->out.getChildren().add(optionCard(o,true))); out.getChildren().add(text("Upgrade your stay in Nashik","custom-group-title")); VBox hotelCards=new VBox(8); NASHIK_HOTELS.forEach(hotel->hotelCards.getChildren().add(hotelCard(hotel))); ScrollPane catalogue=new ScrollPane(hotelCards); catalogue.setFitToWidth(true);catalogue.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);catalogue.setVbarPolicy(ScrollPane.ScrollBarPolicy.AS_NEEDED);catalogue.setMinHeight(280);catalogue.setPrefHeight(280);catalogue.setMaxHeight(280);catalogue.vvalueProperty().addListener((o,oldValue,newValue)->stayCatalogueScroll=newValue.doubleValue());catalogue.getStyleClass().add("custom-hotel-catalogue"); Platform.runLater(()->catalogue.setVvalue(stayCatalogueScroll)); out.getChildren().add(catalogue); out.getChildren().add(text("Room preference","custom-group-title")); PackageCustomizationOptions.options(pkg,PackageOptionType.ROOM).forEach(o->out.getChildren().add(optionCard(o,true)));return out; }
    private Node hotelCard(NashikHotel hotel) { PackageOption option=hotel.option(pkg.id()); boolean selected=option.equals(state.selected(PackageOptionType.STAY)); Label name=text(hotel.name(),"custom-option-title"); Label locality=text(hotel.locality(),"custom-hotel-locality"); Label room=text(hotel.roomType(),"custom-hotel-room"); Label facilities=text(hotel.facilities(),"custom-help"); Label rating=text("★ "+hotel.rating(),"custom-hotel-rating"); VBox details=new VBox(3,name,locality,room,facilities,rating); details.setMinWidth(0); HBox.setHgrow(details,Priority.ALWAYS); Label amount=text("+ ₹"+String.format("%,d",hotel.upgrade())+"\nper traveller","custom-hotel-price"); amount.setAlignment(Pos.CENTER_RIGHT); Button select=new Button(selected?"Selected":"Select"); select.getStyleClass().add(selected?"custom-selected-button":"custom-option-button"); select.setOnAction(e->{state.select(option);state.selectedHotel(hotel.selection(pkg.id()));render();}); Button detailsButton=new Button("View Details"); detailsButton.getStyleClass().add("custom-hotel-details-button"); detailsButton.setOnAction(e->{hotelDetails=hotel;render();}); VBox actions=new VBox(5,amount,select,detailsButton); actions.setAlignment(Pos.CENTER_RIGHT); actions.setMinWidth(136); actions.setPrefWidth(136); actions.setMaxWidth(136); HBox card=new HBox(12,hotelImage(hotel.imageUrl(),186,112),details,actions); card.setAlignment(Pos.CENTER_LEFT); card.getStyleClass().addAll("custom-hotel-card",selected?"custom-option-selected":""); return card; }
    private Node hotelImage(String imageUrl,double width,double height) { Image fallback=new Image(HOTEL_FALLBACK_IMAGE,0,0,true,true,false); Image remote=new Image(imageUrl,0,0,true,true,true); ImageView photo=new ImageView(remote);photo.setPreserveRatio(true);photo.setSmooth(true);photo.setCache(true);photo.setCacheHint(CacheHint.QUALITY);fitImageCover(photo,remote,width,height);remote.widthProperty().addListener((o,a,b)->fitImageCover(photo,remote,width,height));remote.heightProperty().addListener((o,a,b)->fitImageCover(photo,remote,width,height));remote.errorProperty().addListener((o,wasError,isError)->{if(isError){photo.setImage(fallback);fitImageCover(photo,fallback,width,height);}}); StackPane frame=new StackPane(photo);frame.setAlignment(Pos.CENTER);frame.setSnapToPixel(true); frame.setMinSize(width,height);frame.setPrefSize(width,height);frame.setMaxSize(width,height); Rectangle clip=new Rectangle(width,height);clip.setArcWidth(16);clip.setArcHeight(16);frame.setClip(clip);frame.getStyleClass().add("custom-hotel-image"); return frame; }
    private void fitImageCover(ImageView imageView,Image image,double frameWidth,double frameHeight) { if(image==null||image.getWidth()<=0||image.getHeight()<=0)return; double imageRatio=image.getWidth()/image.getHeight(),frameRatio=frameWidth/frameHeight;imageView.setFitWidth(imageRatio<frameRatio?frameWidth:0);imageView.setFitHeight(imageRatio<frameRatio?0:frameHeight); }
    private Node hotelDetailsStep() { NashikHotel hotel=hotelDetails; PackageOption option=hotel.option(pkg.id()); boolean selected=option.equals(state.selected(PackageOptionType.STAY)); VBox details=new VBox(8,text("Hotel details","custom-section-title"),hotelImage(hotel.imageUrl(),460,250),text(hotel.name(),"custom-option-title"),text(hotel.locality(),"custom-hotel-locality"),text("Rating: ★ "+hotel.rating(),"custom-hotel-rating"),text("Room category: "+hotel.roomType(),"custom-hotel-room"),text("Facilities: "+hotel.facilities(),"custom-help"),text("Included: accommodation in the listed room category.  Excluded: booking-time taxes and incidental charges.","custom-help"),text("Upgrade: + ₹"+String.format("%,d",hotel.upgrade())+" per traveller","custom-hotel-price"),text(selected?"Current stay selection: Selected":"Current stay selection: Not selected","custom-help")); details.getStyleClass().add("custom-option-card"); Button back=new Button("Back to Stay");back.getStyleClass().add("package-secondary-button");back.setOnAction(e->{hotelDetails=null;render();});Button select=new Button(selected?"Selected":"Select Hotel");select.getStyleClass().add(selected?"custom-selected-button":"custom-option-button");select.setOnAction(e->{state.select(option);state.selectedHotel(hotel.selection(pkg.id()));render();});HBox actions=new HBox(10,back,spacer(),select);actions.setAlignment(Pos.CENTER_LEFT);return new VBox(12,details,actions); }
    private Node mealsStep() { VBox out=new VBox(12,text("Meals & Preferences","custom-section-title"),text("Keep your included meal plan or choose one curated food experience in Nashik.","custom-help"),mealFilters()); List<PackageOption> meals=PackageCustomizationOptions.options(pkg,PackageOptionType.MEAL); out.getChildren().add(text("Included meals","custom-group-title")); if(meals.isEmpty())out.getChildren().add(text("No included meal plan is configured.","custom-help"));else meals.forEach(o->out.getChildren().add(optionCard(o,true))); out.getChildren().add(text("Upgrade / Choose Food in Nashik","custom-group-title")); GridPane mealCards=new GridPane();mealCards.setHgap(8);mealCards.setVgap(8);mealCards.setPadding(new Insets(2));ColumnConstraints left=new ColumnConstraints();left.setPercentWidth(50);left.setHgrow(Priority.ALWAYS);left.setFillWidth(true);ColumnConstraints right=new ColumnConstraints();right.setPercentWidth(50);right.setHgrow(Priority.ALWAYS);right.setFillWidth(true);mealCards.getColumnConstraints().addAll(left,right);List<NashikMealProvider> filtered=NASHIK_RESTAURANT_MEALS.stream().filter(provider->"All".equals(mealCategory)||provider.categories().contains(mealCategory)).toList();for(int i=0;i<filtered.size();i++)mealCard(mealCards,filtered.get(i),i%2,i/2); if(filtered.isEmpty())mealCards.add(text("No verified restaurant meal options match this category.","custom-help"),0,0,2,1); ScrollPane catalogue=new ScrollPane(mealCards); catalogue.setFitToWidth(true);catalogue.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);catalogue.setVbarPolicy(ScrollPane.ScrollBarPolicy.AS_NEEDED);catalogue.setMinHeight(300);catalogue.setPrefHeight(300);catalogue.setMaxHeight(300);catalogue.getStyleClass().add("custom-hotel-catalogue"); ComboBox<String> pref=new ComboBox<>();pref.getItems().addAll("Standard Vegetarian","Vegetarian","Pure Vegetarian","Maharashtrian","Non-Veg","North Indian","Jain");pref.setValue(state.mealPreference());pref.setOnAction(e->{state.mealPreference(pref.getValue());String category=categoryForPreference(pref.getValue());if(category!=null)mealCategory=category;render();});out.getChildren().addAll(catalogue,text("Meal preference","custom-group-title"),pref);return out; }
    private Node mealFilters() { FlowPane filters=new FlowPane(7,7);filters.getStyleClass().add("custom-meal-filters");for(String category:MEAL_CATEGORIES){Button chip=new Button(category);chip.getStyleClass().add(category.equals(mealCategory)?"custom-meal-filter-active":"custom-meal-filter");chip.setOnAction(e->{mealCategory=category;render();});filters.getChildren().add(chip);}return filters; }
    private String categoryForPreference(String preference) { return switch(preference==null?"":preference) { case "Standard Vegetarian" -> "Vegetarian"; case "Vegetarian", "Pure Vegetarian", "Maharashtrian", "Non-Veg", "North Indian", "Jain" -> preference; default -> null; }; }
    private void mealCard(GridPane cards,NashikMealProvider provider,int column,int row) { PackageOption option=provider.option(pkg.id()); boolean selected=option.equals(state.selected(PackageOptionType.MEAL)); VBox details=new VBox(3,text(provider.name(),"custom-option-title"),text(provider.locality(),"custom-hotel-locality"),text(provider.mealPlan(),"custom-meal-plan"),text(provider.description(),"custom-help"),text(provider.categoryLabel(),"custom-meal-diet")); details.setMinWidth(0); HBox.setHgrow(details,Priority.ALWAYS); Label amount=text("+ ₹"+String.format("%,d",provider.upgrade())+"\nper traveller","custom-hotel-price");amount.setAlignment(Pos.CENTER_RIGHT); Button select=new Button(selected?"Selected":"Select");select.getStyleClass().add(selected?"custom-selected-button":"custom-option-button");select.setOnAction(e->{state.select(option);state.selectedRestaurantMeal(provider.selection(pkg.id()));render();});Button detailsButton=new Button("View Details");detailsButton.getStyleClass().add("custom-hotel-details-button");detailsButton.setOnAction(e->showMealDetails(provider));VBox actions=new VBox(5,amount,select,detailsButton);actions.setAlignment(Pos.CENTER_RIGHT);actions.setMinWidth(92);actions.setPrefWidth(92);actions.setMaxWidth(92);HBox card=new HBox(9,hotelImage(provider.imageUrl(),116,86),details,actions);card.setAlignment(Pos.CENTER_LEFT);card.setMinWidth(0);card.setMaxWidth(Double.MAX_VALUE);card.getStyleClass().addAll("custom-hotel-card","custom-meal-card",selected?"custom-option-selected":"");GridPane.setHgrow(card,Priority.ALWAYS);GridPane.setFillWidth(card,true);cards.add(card,column,row); }
    private void showMealDetails(NashikMealProvider provider) { Dialog<Void> dialog=new Dialog<>();dialog.setTitle("Menu & Details");dialog.setResizable(true);dialog.getDialogPane().getButtonTypes().add(ButtonType.CLOSE);VBox details=new VBox(9,text("Menu & Details","custom-section-title"),hotelImage(provider.imageUrl(),260,170),text(provider.name(),"custom-option-title"),text(provider.locality(),"custom-hotel-locality"),text("Cuisine / Type: "+provider.categoryLabel(),"custom-help"),text("Meal: "+provider.mealPlan(),"custom-help"),text("Timing: "+provider.timing(),"custom-help"),text("Speciality: "+provider.description(),"custom-help"));details.setPrefWidth(285);VBox menu=new VBox(8,text("Menu Highlights","custom-section-title"));provider.menuSections().forEach(section->menu.getChildren().add(menuSection(section)));ScrollPane menuScroll=new ScrollPane(menu);menuScroll.setFitToWidth(true);menuScroll.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);menuScroll.setPrefViewportWidth(330);menuScroll.setPrefViewportHeight(350);menuScroll.getStyleClass().add("custom-menu-scroll");HBox content=new HBox(16,details,menuScroll);content.setPadding(new Insets(10));VBox root=new VBox(10,content,text("Upgrade Price: + ₹"+String.format("%,d",provider.upgrade())+" per traveller","custom-hotel-price"));root.setPadding(new Insets(6));dialog.getDialogPane().setContent(root);dialog.setOnShown(e->{Stage stage=(Stage)dialog.getDialogPane().getScene().getWindow();stage.setX(Screen.getPrimary().getVisualBounds().getMaxX()-stage.getWidth()-24);stage.setY(Screen.getPrimary().getVisualBounds().getMinY()+70);});dialog.showAndWait(); }
    private Node menuSection(MenuSection section) { VBox box=new VBox(4,text(section.title(),"custom-menu-section"));for(MenuItem item:section.items()){Label name=text(item.name(),"custom-help");HBox.setHgrow(name,Priority.ALWAYS);HBox row=new HBox(8,name,text(item.price()==null?"":"₹"+String.format("%,d",item.price()),"custom-menu-price"));box.getChildren().add(row);}box.getStyleClass().add("custom-menu-section-box");return box; }
    private Node optionCard(PackageOption option, boolean single) { boolean chosen=single ? option.equals(state.selected(option.type())) : state.selected(option); String price=option.included()?"Included":option.price()>0?"+ ₹"+String.format("%,d",option.price()):"Optional"; Button action=new Button(chosen?"Selected":single?"Select":"Add");action.getStyleClass().add(chosen?"custom-selected-button":"custom-option-button");action.setDisable(option.mandatory());action.setOnAction(e->{if(single){state.select(option);if(option.type()==PackageOptionType.TRAVEL&&option.label().equalsIgnoreCase("Self Travel"))state.clearActiveTravel();if(option.type()==PackageOptionType.STAY&&option.included())state.selectedHotel(null);if(option.type()==PackageOptionType.MEAL&&option.included())state.selectedRestaurantMeal(null);}else state.toggle(option,!state.selected(option));render();}); VBox copy=new VBox(3,text(option.label(),"custom-option-title"),text(option.description(),"custom-help"));HBox row=new HBox(12,copy,spacer(),text(price,option.included()?"custom-included":"custom-upgrade"),action);row.setAlignment(Pos.CENTER_LEFT);row.getStyleClass().addAll("custom-option-card",chosen?"custom-option-selected":"");if(option.quantityAllowed()&&chosen){Spinner<Integer> quantity=new Spinner<>(1,8,state.quantity(option));quantity.valueProperty().addListener((o,a,v)->{state.quantity(option,v);updateSummary();});row.getChildren().add(quantity);}return row; }
    private Node travellerDetailsPage(){int count=travellerCount();TextField contactName=new TextField(primaryContactDraft==null?"":primaryContactDraft.fullName());TextField contactMobile=new TextField(primaryContactDraft==null?"":primaryContactDraft.mobileNumber());TextField contactEmail=new TextField(primaryContactDraft==null?"":primaryContactDraft.emailAddress());TextField emergency=new TextField(emergencyContactDraft);TextArea notes=new TextArea(assistanceNotesDraft);notes.setPrefRowCount(2);GridPane contactGrid=new GridPane();contactGrid.setHgap(8);contactGrid.setVgap(6);contactGrid.add(text("Full Name","custom-group-title"),0,0);contactGrid.add(text("Mobile Number","custom-group-title"),1,0);contactGrid.add(text("Email Address","custom-group-title"),2,0);contactGrid.add(contactName,0,1);contactGrid.add(contactMobile,1,1);contactGrid.add(contactEmail,2,1);contactGrid.add(text("Emergency Contact Number (optional)","custom-group-title"),0,2);contactGrid.add(text("Special Assistance / Notes (optional)","custom-group-title"),1,2,2,1);contactGrid.add(emergency,0,3);contactGrid.add(notes,1,3,2,1);VBox contactCard=travellerCard("Primary Contact",contactGrid);VBox travellerCards=new VBox(8);List<TravellerForm> forms=new ArrayList<>();for(int i=0;i<count;i++){TravellerForm form=travellerForm(i+1,i<travellerDrafts.size()?travellerDrafts.get(i):null);forms.add(form);travellerCards.getChildren().add(form.card());}Label error=text("","custom-form-error");clearErrorOnEdit(error,contactName,contactMobile,contactEmail,emergency,notes);for(TravellerForm form:forms){clearErrorOnEdit(error,form.name(),form.age(),form.idNumber());clearErrorOnEdit(error,form.gender(),form.idType());}Button back=new Button("Back to Review");back.getStyleClass().add("package-secondary-button");back.setOnAction(e->{travellerDetailsOpen=false;render();});Button next=new Button("Continue to Booking Summary");next.getStyleClass().add("package-search-button");next.setOnAction(e->{PackageBookingDraft draft=validateTravellerDraft(contactName,contactMobile,contactEmail,emergency,notes,forms,error);if(draft!=null){bookingDraft=draft;primaryContactDraft=draft.primaryContact();travellerDrafts=draft.travellers();emergencyContactDraft=draft.emergencyContact();assistanceNotesDraft=draft.specialAssistanceNotes();travellerDetailsOpen=false;bookingSummaryOpen=true;render();}});HBox actions=new HBox(10,back,spacer(),next);VBox page=new VBox(10,text("Traveller Details","custom-section-title"),text("Provide primary contact and traveller information for this local draft. No booking, KYC, payment, or external verification is performed.","custom-help"),contactCard,text("Travellers ("+count+")","custom-group-title"),travellerCards,error,actions);page.getStyleClass().add("traveller-details-page");return page;}
    private TravellerForm travellerForm(int number,PackageTraveller saved){TextField name=new TextField(saved==null?"":saved.fullName());TextField age=new TextField(saved==null?"":Integer.toString(saved.age()));ComboBox<String> gender=new ComboBox<>();gender.getItems().addAll("Male","Female","Other / Prefer not to say");gender.setValue(saved==null?null:saved.gender());ComboBox<String> idType=new ComboBox<>();idType.getItems().addAll("Aadhaar","Passport","Driving Licence","Voter ID","Other");idType.setValue(saved==null?null:saved.idType());TextField idNumber=new TextField(saved==null?"":saved.idNumber());GridPane grid=new GridPane();grid.setHgap(8);grid.setVgap(6);grid.add(text("Full Name","custom-group-title"),0,0);grid.add(text("Age","custom-group-title"),1,0);grid.add(text("Gender","custom-group-title"),2,0);grid.add(text("ID Type","custom-group-title"),3,0);grid.add(text("ID Number","custom-group-title"),4,0);grid.add(name,0,1);grid.add(age,1,1);grid.add(gender,2,1);grid.add(idType,3,1);grid.add(idNumber,4,1);return new TravellerForm(travellerCard("Traveller "+number,grid),name,age,gender,idType,idNumber);}
    private VBox travellerCard(String title,Node content){VBox card=new VBox(8,text(title,"custom-review-card-title"),content);card.getStyleClass().add("traveller-form-card");return card;}
    private PackageBookingDraft validateTravellerDraft(TextField contactName,TextField contactMobile,TextField contactEmail,TextField emergency,TextArea notes,List<TravellerForm> forms,Label error){String name=contactName.getText().trim(),mobile=contactMobile.getText().trim(),email=contactEmail.getText().trim();if(name.isBlank()){error.setText("Enter the primary contact's full name.");return null;}if(!mobile.matches("[6-9][0-9]{9}")){error.setText("Enter a valid 10-digit Indian mobile number.");return null;}if(!email.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$")){error.setText("Enter a valid email address.");return null;}List<PackageTraveller> travellers=new ArrayList<>();for(int i=0;i<forms.size();i++){TravellerForm form=forms.get(i);String travellerName=form.name().getText().trim(),ageText=form.age().getText().trim(),type=form.idType().getValue(),id=form.idNumber().getText().trim();int age;try{age=Integer.parseInt(ageText);}catch(NumberFormatException ex){error.setText("Enter a valid age for Traveller "+(i+1)+".");return null;}if(travellerName.isBlank()||age<1||age>120||form.gender().getValue()==null||type==null||id.isBlank()){error.setText("Complete all required fields for Traveller "+(i+1)+".");return null;}if("Aadhaar".equals(type)&&!id.matches("[0-9]{12}")){error.setText("Aadhaar for Traveller "+(i+1)+" must be 12 digits. This is format validation only.");return null;}travellers.add(new PackageTraveller(travellerName,age,form.gender().getValue(),type,id));}return new PackageBookingDraft(pkg.id(),travellerSnapshot,new PrimaryContact(name,mobile,email),List.copyOf(travellers),emergency.getText().trim(),notes.getText().trim(),travellerSnapshot.totalAmount(),Instant.now());}
    private int travellerCount(){return state.trainSearch()==null?1:Math.max(1,Math.min(10,state.trainSearch().travellers()));}
    private Node bookingSummaryShell(){if(bookingDraft==null){bookingSummaryOpen=false;travellerDetailsOpen=true;return travellerDetailsPage();}VBox left=new VBox(8,text("Booking Summary","custom-section-title"),bookingPackageCard(),bookingContactCard(),bookingTravellersCard(),bookingCustomizationCard(),bookingPriceCard());CheckBox terms=new CheckBox("I have reviewed the package, traveller details, cancellation terms and package conditions.");terms.getStyleClass().add("booking-terms");Label paymentMessage=text(paymentResult==null?"":paymentResult.message(),"custom-form-error");Button back=new Button("Back to Traveller Details");back.getStyleClass().add("package-secondary-button");back.setOnAction(e->{bookingSummaryOpen=false;travellerDetailsOpen=true;render();});Button proceed=new Button("Proceed to Payment");proceed.getStyleClass().add("package-search-button");proceed.setDisable(true);terms.selectedProperty().addListener((o,oldValue,selected)->proceed.setDisable(!selected));proceed.setOnAction(e->preparePayment(proceed,paymentMessage));HBox actions=new HBox(10,back,spacer(),proceed);left.getChildren().addAll(terms,paymentMessage,actions);left.getStyleClass().add("booking-summary-left");return left;}
    private Node demoPaymentSuccessPage(){if(bookingDraft==null){demoPaymentSuccessOpen=false;bookingSummaryOpen=true;return bookingSummaryShell();}VBox details=new VBox(5,reviewLine("Package",pkg.title()),reviewLine("Route",pkg.origin()+" → Nashik"),reviewLine("Travellers",Integer.toString(bookingDraft.travellers().size())),reviewLine("Amount",money(bookingDraft.totalAmount())),reviewLine("Payment Status","Test Payment — Not Razorpay Verified"),reviewLine("Payment Mode","Test Payment"));Label saveMessage=text(demoBookingMessage,"custom-form-error");VBox page=new VBox(10,text("Payment Step Completed","custom-section-title"),text("Payment verification is pending.","custom-help"),bookingCard("Payment Step",details),text("Real payment gateway verification will be enabled with Razorpay integration.","custom-help"));Button back=new Button("Back to Booking Summary");back.getStyleClass().add("package-secondary-button");back.setDisable(demoBookingSaving);back.setOnAction(e->{demoPaymentSuccessOpen=false;bookingSummaryOpen=true;render();});Button confirm=new Button("Confirm Booking");confirm.getStyleClass().add("package-search-button");confirm.setDisable(demoBookingSaving);confirm.setOnAction(e->confirmDemoBooking(confirm,saveMessage));HBox actions=new HBox(10,back,spacer(),confirm);page.getChildren().addAll(saveMessage,actions);page.getStyleClass().add("booking-summary-left");return page;}
    private void confirmDemoBooking(Button confirm,Label message){if(demoBookingSaving){return;}if(confirmedPackageBooking!=null){demoPaymentSuccessOpen=false;bookingConfirmationOpen=true;render();return;}AppSession.User user=AppSession.currentUser();if(user==null){message.setText("Please login before confirming the booking.");return;}if(bookingDraft==null){message.setText("A valid booking draft is required.");return;}if(pendingPackageBooking==null)pendingPackageBooking=PackageBooking.confirmedTest(user.uid(),pkg.title(),pkg.origin()+" → Nashik",pkg.duration(),bookingDraft);demoBookingSaving=true;confirm.setDisable(true);message.setText("Saving booking...");packageBookingRepository.save(pendingPackageBooking,user.idToken()).whenComplete((saved,error)->Platform.runLater(()->{demoBookingSaving=false;if(error!=null){LOGGER.warning("Kumbh package booking persistence failed: "+bookingPersistenceError(error));message.setText("Booking could not be saved. Please try again.");confirm.setDisable(false);return;}confirmedPackageBooking=saved;demoPaymentSuccessOpen=false;bookingConfirmationOpen=true;render();}));}
    private String bookingPersistenceError(Throwable error){Throwable cause=error;while(cause.getCause()!=null)cause=cause.getCause();String message=cause.getMessage();return message==null||message.isBlank()?cause.getClass().getSimpleName():message.replaceAll("[\\r\\n]+"," ");}
    private Node bookingConfirmationPage(){if(confirmedPackageBooking==null){bookingConfirmationOpen=false;demoPaymentSuccessOpen=true;return demoPaymentSuccessPage();}PackageBooking booking=confirmedPackageBooking;VBox details=new VBox(5,reviewLine("Package",booking.packageName()),reviewLine("Booking ID",booking.bookingId()),reviewLine("Route",booking.route()),reviewLine("Travellers",Integer.toString(booking.travellers().size())),reviewLine("Amount",money(booking.finalAmount())),reviewLine("Booking Status","Confirmed"),reviewLine("Payment Status","Test Payment — Verification Pending"));VBox page=new VBox(10,text("✓ Booking Confirmed","custom-section-title"),bookingCard("Kumbh Package Booking",details),text("Razorpay verification will be enabled when the live payment gateway is connected.","custom-help"));Button myBookings=new Button("View My Bookings");myBookings.getStyleClass().add("package-search-button");myBookings.setOnAction(e->openMyBookings.run());Button packages=new Button("Back to Packages");packages.getStyleClass().add("package-secondary-button");packages.setOnAction(e->{bookingConfirmationOpen=false;navigate.accept(new KumbhPackagesPage(navigate,openMyBookings).create());});HBox actions=new HBox(10,packages,spacer(),myBookings);page.getChildren().add(actions);page.getStyleClass().add("booking-summary-left");return page;}
    private Node bookingPackageCard(){VBox content=new VBox(4,reviewLine("Package",pkg.title()),reviewLine("Package ID",bookingDraft.packageId()),reviewLine("Route",pkg.origin()+" → Nashik"),reviewLine("Duration",pkg.duration()),reviewLine("Travellers",Integer.toString(bookingDraft.travellers().size())));return bookingCard("Package Details",content);}
    private Node bookingContactCard(){PrimaryContact contact=bookingDraft.primaryContact();VBox content=new VBox(4,reviewLine("Full Name",contact.fullName()),reviewLine("Mobile",contact.mobileNumber()),reviewLine("Email",contact.emailAddress()));if(!bookingDraft.emergencyContact().isBlank())content.getChildren().add(reviewLine("Emergency Contact",bookingDraft.emergencyContact()));if(!bookingDraft.specialAssistanceNotes().isBlank())content.getChildren().add(text("Notes: "+bookingDraft.specialAssistanceNotes(),"custom-review-detail"));return bookingCard("Primary Contact",content);}
    private Node bookingTravellersCard(){VBox content=new VBox(5);for(int i=0;i<bookingDraft.travellers().size();i++){PackageTraveller traveller=bookingDraft.travellers().get(i);content.getChildren().add(text("Traveller "+(i+1)+"  •  "+traveller.fullName()+"\nAge: "+traveller.age()+"  •  "+traveller.gender()+"\n"+traveller.idType()+": "+maskId(traveller.idType(),traveller.idNumber()),"custom-review-detail"));}return bookingCard("Travellers",content);}
    private Node bookingCustomizationCard(){VBox content=new VBox(4);bookingDraft.customizationSnapshot().selections().forEach((key,value)->{if(!"MEAL_PREFERENCE".equals(key))content.getChildren().add(reviewLine(bookingSelectionLabel(key),bookingSelectionValue(value)));});return bookingCard("Customization Summary",content);}
    private Node bookingPriceCard(){VBox content=new VBox(5);bookingDraft.customizationSnapshot().componentPrices().forEach((name,amount)->content.getChildren().add(reviewLine(name,money(amount))));content.getChildren().addAll(new Separator(),reviewLine("Final Payable Amount",money(bookingDraft.totalAmount()),"custom-review-total"));return bookingCard("Price Breakdown",content);}
    private Node bookingCard(String title,Node content){VBox card=new VBox(7,text(title,"custom-review-card-title"),content);card.getStyleClass().add("booking-summary-card");return card;}
    private String bookingSelectionLabel(String key){return key.replace("RESTAURANT_MEAL","Meals").replace("LOCAL_TRANSPORT","Local Transport").replace("TRAVEL_CLASS","Travel Class").replace('_',' ');}
    private String bookingSelectionValue(String value){int separator=value.indexOf('|');return separator<0?value:value.substring(separator+1).replace("|"," • ");}
    private String maskId(String type,String id){String digits=id==null?"":id.trim();if(digits.length()<=4)return "XXXX";String suffix=digits.substring(digits.length()-4);return "Aadhaar".equalsIgnoreCase(type)?"XXXX-XXXX-"+suffix:"XXXX-"+suffix;}
    private void preparePayment(Button proceed,Label message){if(paymentAttemptInProgress){message.setText("A payment attempt is already in progress.");return;}if(bookingDraft==null||bookingDraft.totalAmount()<=0){message.setText("A valid booking draft and payable amount are required.");return;}if(DEMO_PACKAGE_PAYMENT){demoPaymentReference="DEMO-PKG-"+System.currentTimeMillis();bookingSummaryOpen=false;demoPaymentSuccessOpen=true;render();return;}PaymentConfig paymentConfig=PaymentConfig.load();if(!paymentConfig.isEnabled()){String reason=paymentConfig.configurationIssue();LOGGER.warning("Kumbh package payment unavailable: "+reason);message.setText("Payment service is not configured.");return;}AppSession.User user=AppSession.currentUser();if(user==null){message.setText("Please login before proceeding to payment.");return;}paymentAttemptInProgress=true;proceed.setDisable(true);message.setText("Preparing secure payment...");String reference="PKG-DRAFT-"+UUID.randomUUID().toString().substring(0,8);PaymentRequest request=PaymentRequest.builder().userId(user.uid()).bookingId(reference).moduleType(PaymentModuleType.PACKAGE).itemId(bookingDraft.packageId()).title("Kumbh Package — "+pkg.title()).description("Package customization payment preparation").amount(BigDecimal.valueOf(bookingDraft.totalAmount())).currency("INR").customerName(bookingDraft.primaryContact().fullName()).customerEmail(bookingDraft.primaryContact().emailAddress()).customerPhone(bookingDraft.primaryContact().mobileNumber()).metadata("packageId",bookingDraft.packageId()).metadata("travellerCount",Integer.toString(bookingDraft.travellers().size())).metadata("bookingDraftReference",reference).build();PaymentServiceFactory.get().startPayment(proceed.getScene().getWindow(),request).whenComplete((result,throwable)->Platform.runLater(()->{paymentAttemptInProgress=false;paymentResult=result==null?PaymentResult.failed("Payment could not be initiated.","PAYMENT_INIT_FAILED"):result;message.setText(paymentResult.message());proceed.setDisable(false);}));}
    private void clearErrorOnEdit(Label error,TextInputControl... controls){for(TextInputControl control:controls)control.textProperty().addListener((o,oldValue,newValue)->error.setText(""));}
    private void clearErrorOnEdit(Label error,ComboBox<?>... controls){for(ComboBox<?> control:controls)control.valueProperty().addListener((o,oldValue,newValue)->error.setText(""));}
    private Node navigation() { Button back=new Button("Back");back.getStyleClass().add("package-secondary-button");back.setOnAction(e->{if(step==0)backToPackageDetails.run();else{step--;render();}});Button next=new Button(step==STEPS.size()-1?"Continue to Traveller Details":"Continue");next.getStyleClass().add("package-search-button");next.setOnAction(e->{if(step==STEPS.size()-1)openTravellerDetails(state.snapshot(pricing.calculate(pkg,state)));else if(validStep()){step++;render();}});HBox row=new HBox(10,back,spacer(),next);return row; }
    private boolean validStep(){ if(step==0&&!PackageCustomizationOptions.options(pkg,PackageOptionType.TRAVEL).isEmpty()&&state.selected(PackageOptionType.TRAVEL)==null)return missing("Please select a travel preference."); if(step==1&&!pkg.stay().equalsIgnoreCase("No Stay")&&!PackageCustomizationOptions.options(pkg,PackageOptionType.STAY).isEmpty()&&state.selected(PackageOptionType.STAY)==null)return missing("Please select a stay preference."); return true; }
    private boolean missing(String message){new Alert(Alert.AlertType.WARNING,message,ButtonType.OK).showAndWait();return false;}
    private void updateSummary(){if(travellerDetailsOpen||bookingSummaryOpen||demoPaymentSuccessOpen||bookingConfirmationOpen){updateTravellerSummary();return;}PackagePricingService.Pricing p=pricing.calculate(pkg,state);summary.getChildren().setAll(text("Your Package","custom-summary-title"),text("Current customisation price per traveller","custom-help"));p.components().forEach((name,value)->summary.getChildren().add(summaryRow(name,value)));summary.getChildren().addAll(new Separator(),summaryRow("Current Total",p.total()),text("Taxes/payment fees calculated during final booking.","custom-help"));}
    private void updateTravellerSummary(){if(travellerSnapshot==null)return;VBox items=new VBox(5,text("Booking Snapshot","custom-summary-title"),text(travellerSnapshot.packageCode(),"custom-option-title"),text(pkg.origin()+" → Nashik  •  "+pkg.duration(),"custom-help"),text("Travellers: "+travellerCount(),"custom-help"),new Separator(),summaryRow("Current Total",travellerSnapshot.totalAmount()));summary.getChildren().setAll(items);}
    private Node summaryRow(String label,int amount){Label component=text(label,"custom-summary-label");component.setMaxWidth(Double.MAX_VALUE);HBox.setHgrow(component,Priority.ALWAYS);Label price=text((amount==0?"Included":"₹"+String.format("%,d",amount)),"custom-summary-price");price.setWrapText(false);price.setMinWidth(82);price.setPrefWidth(82);price.setMaxWidth(82);price.setAlignment(Pos.CENTER_RIGHT);HBox r=new HBox(8,component,price);r.setAlignment(Pos.CENTER_LEFT);return r;}
    private Node review(){PackagePricingService.Pricing p=pricing.calculate(pkg,state);FlowPane cards=new FlowPane(8,8);cards.getStyleClass().add("custom-review-grid");cards.getChildren().addAll(reviewTravelCard(),reviewStayCard(),reviewMealsCard(),reviewTransportCard(),reviewExperiencesCard(),reviewSightseeingCard(),reviewAddonsCard(),reviewPriceCard(p));VBox page=new VBox(8,text("Review Your Kumbh Package","custom-section-title"),reviewPackageInfo(),cards,text("No booking, payment, or traveller information is created in this step.","custom-help"));page.getStyleClass().add("custom-review-page");return page;}
    private Node reviewPackageInfo(){VBox info=new VBox(3,text(pkg.title(),"custom-review-package-title"),text("Package ID: "+pkg.id(),"custom-help"),text("Route: "+pkg.origin()+" → Nashik  •  Duration: "+pkg.duration(),"custom-help"));info.getStyleClass().add("custom-review-package-info");return info;}
    private Node reviewTravelCard(){VBox content=new VBox(5);PackageOption travel=state.selected(PackageOptionType.TRAVEL);PackageOption travelClass=state.selected(PackageOptionType.TRAVEL_CLASS);content.getChildren().add(reviewLine(travel==null?"No travel selected":travel.label(),travel!=null&&travel.included()?"Included":""));if(travelClass!=null)content.getChildren().add(reviewLine(travelClass.label(),travelClass.included()?"Included":money(travelClass.price())));if(state.selectedFlight()!=null){FlightOption flight=state.selectedFlight();content.getChildren().add(text(flight.airline()+" "+flight.flightNumber()+"\n"+flight.departure().airportCode()+" → "+flight.arrival().airportCode()+"  •  "+flight.departure().scheduledTime()+" → "+flight.arrival().scheduledTime(),"custom-review-detail"));}if(state.selectedTrain()!=null){TrainJourney train=state.selectedTrain();content.getChildren().add(text(train.trainName()+" "+train.trainNumber()+"\n"+train.fromStationCode()+" → "+train.toStationCode()+"  •  "+train.departureTime()+" → "+train.arrivalTime(),"custom-review-detail"));}if(state.selectedBus()!=null){BusJourney bus=state.selectedBus();content.getChildren().add(text(displayBusName(bus.operator())+" • "+bus.type().label()+"\n"+bus.fromCity()+" → "+bus.toCity()+"  •  "+bus.departureTime()+" → "+bus.arrivalTime(),"custom-review-detail"));}return reviewCard("Travel",content);}
    private Node reviewStayCard(){VBox content=new VBox(5);if(state.selectedHotel()!=null){HotelStaySelection hotel=state.selectedHotel();content.getChildren().add(reviewLine(hotel.hotelName(),money(hotel.upgradeCharge())));content.getChildren().add(text("Location: "+hotel.locality(),"custom-review-detail"));}else{PackageOption stay=state.selected(PackageOptionType.STAY);content.getChildren().add(reviewLine(stay==null?"No stay selected":stay.label(),stay==null?"":stay.included()?"Included":money(stay.price())));}PackageOption room=state.selected(PackageOptionType.ROOM);if(room!=null)content.getChildren().add(reviewLine("Room: "+room.label(),room.included()?"Included":money(room.price())));return reviewCard("Stay",content);}
    private Node reviewMealsCard(){VBox content=new VBox(5);if(state.selectedRestaurantMeal()!=null){RestaurantMealSelection meal=state.selectedRestaurantMeal();content.getChildren().add(reviewLine(meal.restaurantName()+" — "+meal.mealPlan(),money(meal.upgradeCharge())));content.getChildren().add(text(meal.locality(),"custom-review-detail"));}else{PackageOption meal=state.selected(PackageOptionType.MEAL);content.getChildren().add(reviewLine(meal==null?"No meal selected":meal.label(),meal==null?"":meal.included()?"Included":money(meal.price())));}return reviewCard("Meals",content);}
    private Node reviewTransportCard(){LocalTransportSelection transport=state.selectedLocalTransport();VBox content=new VBox(5,reviewLine(transport==null?"No local transport selected":transport.name(),transport==null?"":transport.upgradeCharge()==0?"Included":money(transport.upgradeCharge())));return reviewCard("Local Transport",content);}
    private Node reviewExperiencesCard(){VBox content=new VBox(5);for(KumbhExperienceSelection experience:state.selectedKumbhExperiences())content.getChildren().add(reviewLine("✓ "+experience.name(),experience.included()?"Included":money(experience.upgradeCharge())));return reviewCard("Kumbh Experience",content);}
    private Node reviewSightseeingCard(){VBox content=new VBox(5);if(state.selectedSightseeing().isEmpty())content.getChildren().add(text("No optional sightseeing selected","custom-review-empty"));else for(SightseeingSelection sightseeing:state.selectedSightseeing())content.getChildren().add(reviewLine("✓ "+sightseeing.name(),money(sightseeing.packageCharge())));return reviewCard("Nashik Sightseeing",content);}
    private Node reviewAddonsCard(){VBox content=new VBox(5);if(state.selectedPackageAddons().isEmpty())content.getChildren().add(text("No optional Puja & Add-ons selected","custom-review-empty"));else for(PackageAddonSelection addon:state.selectedPackageAddons())content.getChildren().add(reviewLine("✓ "+addon.name(),money(addon.upgradeCharge())));return reviewCard("Puja & Add-ons",content);}
    private Node reviewPriceCard(PackagePricingService.Pricing pricing){VBox content=new VBox(5);pricing.components().forEach((name,amount)->content.getChildren().add(reviewLine(name,money(amount))));Separator divider=new Separator();divider.getStyleClass().add("custom-review-divider");content.getChildren().addAll(divider,reviewLine("Current Total",money(pricing.total()),"custom-review-total"));return reviewCard("Price Summary",content);}
    private Node reviewCard(String title,Node content){VBox card=new VBox(6,text(title,"custom-review-card-title"),content);card.setMinWidth(340);card.setPrefWidth(430);card.setMaxWidth(Double.MAX_VALUE);card.getStyleClass().add("custom-review-card");return card;}
    private Node reviewLine(String name,String value){return reviewLine(name,value,"custom-review-line");}
    private Node reviewLine(String name,String value,String css){Label left=text(name,css);left.setMaxWidth(Double.MAX_VALUE);HBox.setHgrow(left,Priority.ALWAYS);Label right=text(value,css);right.setWrapText(false);right.setAlignment(Pos.CENTER_RIGHT);HBox line=new HBox(12,left,right);line.setAlignment(Pos.CENTER_LEFT);return line;}
    private String money(int amount){return amount==0?"Included":"₹"+String.format("%,d",amount);}
    private void openTravellerDetails(PackageCustomizationSnapshot snapshot){travellerSnapshot=snapshot;bookingSummaryOpen=false;travellerDetailsOpen=true;render();}
    private String label(PackageOptionType type){return switch(type){case TRAVEL->"Travel";case TRAVEL_CLASS->"Travel class";case STAY->"Stay";case ROOM->"Room";case MEAL->"Meals";case LOCAL_TRANSPORT->"Local transport";case KUMBH->"Kumbh facilities";case SIGHTSEEING->"Sightseeing";case PUJA_ADDON->"Puja & add-ons";};}
    private Label text(String s,String css){Label l=new Label(s);l.setWrapText(true);l.getStyleClass().add(css);return l;}private Region spacer(){Region r=new Region();HBox.setHgrow(r,Priority.ALWAYS);return r;}
    private static MenuSection section(String title,MenuItem... items) { return new MenuSection(title,List.of(items)); } private static MenuItem item(String name,Integer price) { return new MenuItem(name,price); }
    private record KumbhExperience(String id,String name,String description,boolean included,int upgrade) { PackageOption option(String packageId) { return new PackageOption(packageId+":KUMBH:"+id,PackageOptionType.KUMBH,name,description,upgrade,included,included,false); } KumbhExperienceSelection selection(String packageId) { return new KumbhExperienceSelection(packageId+":KUMBH:"+id,name,description,included,upgrade); } }
    private record NashikSightseeing(String id,String name,String location,String description,String duration,int packageCharge) { PackageOption option(String packageId) { return new PackageOption(packageId+":SIGHTSEEING:"+id,PackageOptionType.SIGHTSEEING,name,description+" · "+location,packageCharge,false,false,false); } SightseeingSelection selection(String packageId) { return new SightseeingSelection(packageId+":SIGHTSEEING:"+id,name,location,description,duration,packageCharge); } }
    private record PackageAddon(String id,String name,String description,String category,int upgrade) { PackageOption option(String packageId) { return new PackageOption(packageId+":PUJA_ADDON:"+id,PackageOptionType.PUJA_ADDON,name,description,upgrade,false,false,false); } PackageAddonSelection selection(String packageId) { return new PackageAddonSelection(packageId+":PUJA_ADDON:"+id,name,description,category,upgrade); } }
    private record TravellerForm(VBox card,TextField name,TextField age,ComboBox<String> gender,ComboBox<String> idType,TextField idNumber) { }
    private record NashikHotel(String name,String locality,String roomType,String facilities,String rating,int upgrade,String imageUrl) { PackageOption option(String packageId) { return new PackageOption(packageId+":STAY:hotel:"+name.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-"),PackageOptionType.STAY,name,roomType+" · "+locality,upgrade,false,false,false); } HotelStaySelection selection(String packageId) { return new HotelStaySelection(packageId+":hotel:"+name.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-"),name,locality,roomType,rating,facilities,imageUrl,upgrade); } }
    private record NashikMealProvider(String name,String locality,String mealPlan,String description,String categoryLabel,Set<String> categories,int upgrade,String imageUrl,List<MenuSection> menuSections) { String timing() { return mealPlan.toLowerCase(Locale.ROOT).contains("misal")?"Breakfast or lunch":mealPlan.toLowerCase(Locale.ROOT).contains("dinner")?"Lunch or dinner":"Lunch or dinner"; } PackageOption option(String packageId) { return new PackageOption(packageId+":MEAL:restaurant:"+name.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-")+":"+mealPlan.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-"),PackageOptionType.MEAL,name+" — "+mealPlan,description+" · "+locality,upgrade,false,false,false); } RestaurantMealSelection selection(String packageId) { return new RestaurantMealSelection(packageId+":meal:"+name.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-"),name,locality,mealPlan,categoryLabel,upgrade); } }
    private record MenuSection(String title,List<MenuItem> items) { } private record MenuItem(String name,Integer price) { }
}
